import { o, sc } from './kit'

// Brew Lane Café — Colombo 07
export const CAFE = [
  sc({
    id: 'cafe_open', biz: 'cafe', rounds: [1, 1], weeks: 4,
    title: 'The chain down the road is taking your mornings',
    story: [
      'Same street. Bigger sign. Free Wi-Fi.',
      'Your 8 a.m. rush has become a trickle. Today you choose what Brew Lane stands for.',
    ],
    options: [
      o('Win on price', 'Cut prices by 5% and put it on a big board outside.',
        { price: 0.95, market: 1.2, boost: 0.3, brand: 3, efficiency: 4 },
        'A red “Better coffee, better price” board goes up on the lane.',
        'Office workers start comparing receipts. Each cup now earns you less.'),
      o('Go specialty', 'Single-origin beans and retrained baristas. LKR 600K, prices up 5%.',
        { cash: -600_000, price: 1.05, quality: 7, brand: 3, set: ['specialty'] },
        'You fly in a roaster for a weekend workshop. The coffee tastes different now.',
        'Some regulars wince at the new prices. Coffee lovers start to notice.'),
      o('Own the study crowd', 'Plugs, long tables, open till 11 p.m. LKR 400K.',
        { cash: -400_000, market: 1.22, fixed: 15_000, brand: 4, set: ['students'] },
        'Long tables, a plug at every seat, a sign that says “Stay as long as you like.”',
        'By the second week, A/L students fill every table after 4 p.m.'),
      o('Cut to survive', 'Close at 6 p.m. and run one barista short. Save about 12% on costs.',
        { fixedPct: 0.88, morale: -8, quality: -3, efficiency: 6 },
        'Shorter hours. Leaner shifts. The numbers look healthier on paper.',
        'The team is stretched. Queues get longer at lunch.'),
    ],
  }),

  sc({
    id: 'cafe_barista', biz: 'cafe', rounds: [2, 8], weeks: 3,
    title: 'Your best barista has a job offer in Dubai',
    story: ['Nadee makes the best flat white in Colombo. Customers ask for her by name.', 'She leaves in two weeks unless something changes.'],
    options: [
      o('Match the salary', 'Adds LKR 18K a week to costs. She stays.',
        { fixed: 18_000, morale: 6, quality: 3 },
        'You match the offer. Nadee stays.',
        'The rest of the team quietly wonders what they would need to do to get a raise.'),
      o('Make her head barista', 'A title plus 5% of profits. Costs you margin, not salary.',
        { margin: -0.02, morale: 12, quality: 6, set: ['headbarista'] },
        'Nadee becomes head barista with a share of the profits.',
        'She starts training everyone. The whole team gets better.'),
      o('Let her go, hire two juniors', 'Cheaper, but quality dips while they learn.',
        { fixed: -6_000, cash: -80_000, quality: -6, efficiency: -3, capacity: 1.05 },
        'Nadee leaves with a cake and a hug. Two juniors start on Monday.',
        'The coffee is a little inconsistent for a while.'),
      o('Ask her to train others first', 'Pay a LKR 150K bonus to train the team before she goes.',
        { cash: -150_000, quality: 4, morale: -2 },
        'Nadee spends her last two weeks teaching everything she knows.',
        'She leaves. Her recipes stay.'),
    ],
  }),

  sc({
    id: 'cafe_delivery', biz: 'cafe', rounds: [2, 10], weeks: 4, not: ['delivery', 'ownorders'],
    title: 'Delivery apps want Brew Lane on their platforms',
    story: ['Half of Colombo now orders coffee to their desks.', 'The apps take a commission on every order.'],
    options: [
      o('Join every app', 'Reach thousands more people. Apps keep about 25% of each order.',
        { market: 1.22, margin: -0.06, brand: 3, set: ['delivery'] },
        'Brew Lane goes live on every app in Colombo.',
        'The order printer never stops. Each order earns you much less.'),
      o('Build your own WhatsApp ordering', 'LKR 250K to set up. Smaller reach, no commission.',
        { cash: -250_000, market: 1.08, efficiency: -2, set: ['ownorders'] },
        'A WhatsApp number on every cup. A rider on a bike.',
        'Orders come slowly at first, but you keep every rupee.'),
      o('Join with a delivery-only menu', 'A cheaper, simpler menu just for delivery.',
        { market: 1.16, margin: -0.03, quality: -2, set: ['delivery'] },
        'A shorter delivery menu built to travel well.',
        'Cheaper to make. Less special than the real thing.'),
      o('Stay dine-in only', 'Spend LKR 400K making the café worth visiting instead.',
        { cash: -400_000, quality: 5, brand: 3 },
        'New lights, plants and better chairs. You bet on the experience.',
        'People who come in stay longer. Fewer people find you.'),
    ],
  }),

  sc({
    id: 'cafe_delivery_fee', biz: 'cafe', rounds: [4, 14], weeks: 4, needs: ['delivery'],
    title: 'The delivery app just raised its commission to 35%',
    story: ['An email at midnight: “New partner terms take effect Monday.”', 'Delivery is now a third of your orders.'],
    options: [
      o('Accept it', 'Keep the orders. Lose more on each one.',
        { margin: -0.025, brand: 1 },
        'You sign the new terms.', 'Orders keep flowing. The profit on each one shrinks again.'),
      o('Raise app prices by 15%', 'Pass the cost on. Some customers will notice.',
        { price: 1.04, customers: 0.95 },
        'App prices go up 15%.', 'A few one-star reviews mention price. Most people keep ordering.'),
      o('Move customers to your own ordering', 'LKR 300K for a 10%-off code on every delivery bag.',
        { cash: -300_000, margin: 0.02, brand: 2, set: ['ownorders'] },
        'Every bag now carries a card: “Order direct, save 10%.”',
        'Slowly, regulars start messaging you directly.'),
      o('Leave the app', 'Lose the reach. Keep your margins.',
        { market: 0.88, margin: 0.03, clear: ['delivery'] },
        'You switch the app off.', 'The printer goes quiet. The margins come back.'),
    ],
  }),

  sc({
    id: 'cafe_influencer', biz: 'cafe', rounds: [3, 12], weeks: 3,
    title: 'A TikToker with 400K followers wants free coffee for a month',
    story: ['In exchange, “maybe a video or two.”', 'Her last café video got 1.2 million views.'],
    options: [
      o('Say yes', 'Free coffee for a month. The video could go either way.',
        { cash: -120_000, boost: 0.45, brand: 7 },
        'She films her first visit. 900K views by Sunday.',
        'A wave of new faces arrives, phones out.'),
      o('Pay for a proper story', 'LKR 350K for a series on where your beans come from.',
        { cash: -350_000, brand: 11, boost: 0.3, market: 1.04 },
        'She visits the estate in Haputale with your roaster.',
        'The series makes people care about where their coffee comes from.'),
      o('Say no, feature your regulars', 'LKR 80K to film your own customers’ stories instead.',
        { cash: -80_000, morale: 3, brand: 4 },
        'You film the retired teacher who has come every morning for eight years.',
        'It is smaller, but it feels real. Regulars share it.'),
      o('Invite her to work a shift', 'She makes coffee behind the bar for a day. LKR 150K.',
        { cash: -150_000, boost: 0.35, brand: 8, morale: 4 },
        'She burns the milk twice. The video is hilarious.',
        'The team loves it. So does the internet.'),
    ],
  }),

  sc({
    id: 'cafe_beans', biz: 'cafe', rounds: [2, 12], weeks: 4,
    title: 'Coffee bean prices just jumped 30%',
    story: ['A bad harvest in Brazil. Every café in Colombo pays more from Monday.'],
    options: [
      o('Absorb the cost', 'Keep prices the same. Your profit per cup falls.',
        { margin: -0.025, brand: 3 },
        'Prices stay where they are.', 'Customers do not notice. Your accountant does.'),
      o('Raise prices by 5%', 'Protect your margin. Some people will grumble.',
        { price: 1.05, brand: -2 },
        'New menu boards go up.', 'A few regulars switch to tea. Most stay.'),
      o('Switch to Sri Lankan arabica', 'Local beans from Haputale, and tell the story. LKR 200K.',
        { cash: -200_000, margin: -0.01, brand: 6, quality: 2, set: ['local'] },
        '“Grown 180 km from this cup.” The new sign starts conversations.',
        'Costs are steadier. The story sells.'),
      o('Make cups slightly smaller', 'Same price, 10% less coffee. Cheaper, but risky.',
        { margin: 0.02, quality: -5, brand: -4 },
        'The new cups are 10% smaller.', 'Someone posts a photo comparing the old cup and the new one.'),
    ],
  }),

  sc({
    id: 'cafe_space', biz: 'cafe', rounds: [4, 12], weeks: 5, when: s => s.customers > s.capacity * 0.45,
    title: 'The shop next door is for rent',
    story: ['Same lane. Same footfall. LKR 2 million to fit it out.', 'Busy afternoons, you are already turning people away.'],
    options: [
      o('Take it and double your seating', 'LKR 1M cash, LKR 1.5M loan, LKR 80K more rent a week.',
        { cash: -1_000_000, debt: 1_500_000, capacity: 1.55, fixed: 80_000, assets: 1_500_000, market: 1.12, set: ['expanded'] },
        'Walls come down. Brew Lane is twice the size.', 'Now you need twice the customers.'),
      o('Turn it into a coworking space', 'Desks rented by the hour. LKR 2M and LKR 90K a week.',
        { cash: -800_000, debt: 1_200_000, fixed: 90_000, market: 1.2, capacity: 1.2, assets: 1_000_000, set: ['cowork'] },
        'Twenty desks, fast Wi-Fi, and coffee next door.', 'Freelancers start booking monthly passes.'),
      o('Sublet it to a bakery', 'They pay rent and send customers your way. LKR 300K to set up.',
        { cash: -300_000, market: 1.04, brand: 2, set: ['bakery'] },
        'A sourdough bakery opens next door.', 'Croissant next door, coffee here. People start doing both.'),
      o('Open a campus kiosk instead', 'A small kiosk at a university. LKR 1.2M, LKR 45K a week.',
        { cash: -1_200_000, fixed: 45_000, market: 1.14, capacity: 1.15, brand: 3, set: ['kiosk'] },
        'A Brew Lane kiosk opens near a campus library.', 'Students who try it start walking to the main café too.'),
    ],
  }),

  sc({
    id: 'cafe_cowork_noise', biz: 'cafe', rounds: [6, 15], weeks: 3, needs: ['cowork'],
    title: 'Remote workers say the café is too loud',
    story: ['Your coworking members pay monthly. Your café customers pay by the cup.', 'They want different things.'],
    options: [
      o('Soundproof the wall', 'LKR 500K. Both groups get what they want.',
        { cash: -500_000, quality: 5, brand: 3, assets: 300_000 },
        'Builders seal the shared wall.', 'Silence on one side, chatter on the other.'),
      o('Add phone booths and quiet hours', 'LKR 200K. A compromise.',
        { cash: -200_000, quality: 2, morale: 1 },
        'Two phone booths and a “quiet till noon” rule.', 'Most people are happy. Some are not.'),
      o('Raise membership prices, add perks', 'Free coffee for members, 25% higher fees.',
        { price: 1.04, margin: -0.01, brand: 2 },
        'Members get unlimited coffee and pay more for it.', 'A few leave. The ones who stay are loyal.'),
      o('Choose the café', 'Close coworking, reopen it as more café seating.',
        { capacity: 1.1, market: 0.9, fixed: -30_000, clear: ['cowork'] },
        'The desks go. More café tables come in.', 'Simpler, louder, busier.'),
    ],
  }),

  sc({
    id: 'cafe_kiosk_deal', biz: 'cafe', rounds: [7, 15], weeks: 4, needs: ['kiosk'],
    title: 'The university wants Brew Lane in every building',
    story: ['Five kiosks across campus. Exclusive for two years.', 'They want a 12% cut of sales.'],
    options: [
      o('Sign for all five', 'LKR 2.5M to open, big growth, thinner margins.',
        { cash: -1_000_000, debt: 1_500_000, market: 1.3, capacity: 1.3, fixed: 80_000, margin: -0.02, assets: 1_200_000 },
        'Five kiosks open over two weekends.', 'Brew Lane becomes the campus coffee.'),
      o('Sign for two, test first', 'LKR 900K. Learn before you scale.',
        { cash: -900_000, market: 1.12, capacity: 1.12, fixed: 40_000, assets: 500_000, efficiency: 3 },
        'Two more kiosks. You watch the numbers closely.', 'Steady, careful growth.'),
      o('Negotiate the cut down to 6%', 'Slower deal, better terms.',
        { market: 1.06, margin: 0.01, boost: 0.1 },
        'Three meetings later, they agree to 8%.', 'One new kiosk opens next month.'),
      o('Walk away', 'Keep the one kiosk you have and protect the café.',
        { quality: 3, morale: 3 },
        'You thank them and decline.', 'Your team has more time for the main café.'),
    ],
  }),

  sc({
    id: 'cafe_evening', biz: 'cafe', rounds: [4, 13], weeks: 4,
    title: 'After 6 p.m., Brew Lane is empty',
    story: ['You pay rent for 24 hours a day. You make money for 10.'],
    options: [
      o('Live music nights', 'LKR 20K a week for musicians. Friday and Saturday nights.',
        { fixed: 20_000, boost: 0.2, brand: 6, market: 1.05, morale: -2 },
        'An acoustic duo plays Friday nights.', 'People start staying for one more coffee.'),
      o('Rent the space for events', 'Book launches, workshops, birthday parties.',
        { market: 1.05, margin: 0.02, brand: 1 },
        'Event bookings fill your evenings.', 'Good money, though regulars sometimes find it closed.'),
      o('Close at 6 and save', 'Cut electricity and evening shifts.',
        { fixedPct: 0.93, morale: 4 },
        'Lights off at six.', 'Your team gets their evenings back.'),
      o('Launch a dessert bar', 'Hire a pastry chef for LKR 40K a week.',
        { fixed: 40_000, price: 1.05, market: 1.12, quality: 3 },
        'Waffles, tiramisu and affogato after 6 p.m.', 'Couples start coming for dessert dates.'),
    ],
  }),

  sc({
    id: 'cafe_review', biz: 'cafe', rounds: [3, 14], weeks: 3,
    title: 'A viral review calls your coffee “overpriced and burnt”',
    story: ['4,000 likes. 600 comments. Some agree, some defend you.'],
    options: [
      o('Apologise and invite them back', 'A public apology and a free coffee day. LKR 150K.',
        { cash: -150_000, brand: 5, boost: 0.15 },
        'You post an honest reply and announce a free-coffee Saturday.',
        'The queue goes around the corner.'),
      o('Challenge the chain to a blind taste test', 'LKR 200K, filmed live. Only works if your coffee is better.',
        s => (s.quality >= 62 ? { cash: -200_000, brand: 14, boost: 0.3 } : { cash: -200_000, brand: -6, boost: 0.1 }),
        'Fifty strangers. Two unmarked cups. Cameras rolling.',
        'The result goes online within the hour.'),
      o('Say nothing, fix the roast', 'LKR 250K on a new grinder and roast profile.',
        { cash: -250_000, quality: 8, assets: 150_000 },
        'You stay quiet and fix the problem.', 'Within a month the coffee is noticeably better.'),
      o('Reply with humour', 'A funny post. Free, but risky.',
        { brand: 5, morale: 3, boost: 0.1 },
        '“We burnt the coffee. We also burnt our pride. Come try round two.”',
        'People laugh. Most of them are on your side.'),
    ],
  }),

  sc({
    id: 'cafe_loyalty', biz: 'cafe', rounds: [3, 13], weeks: 5, not: ['subscription'],
    title: 'How do you make people come back?',
    story: ['The average customer visits once a month.', 'The chain has an app with points. You have a smile.'],
    options: [
      o('Build a loyalty app', 'LKR 600K. Points, birthday coffee and pre-ordering.',
        { cash: -600_000, market: 1.06, brand: 4, efficiency: 3, assets: 300_000, set: ['app'] },
        'The Brew Lane app goes live.', 'Pre-orders cut the morning queue in half.'),
      o('Paper stamp cards', 'LKR 30K. Buy 9, get 1 free.',
        { cash: -30_000, brand: 3, boost: 0.15, margin: -0.01 },
        'Little brown cards with a coffee-bean stamp.', 'Simple, and people love collecting stamps.'),
      o('Coffee subscription', 'LKR 9,900 a month for one coffee a day.',
        { market: 1.12, price: 0.96, brand: 3, set: ['subscription'] },
        'You launch “One a Day” at LKR 9,900 a month.', '400 people sign up in the first week.'),
      o('Train the team instead', 'LKR 250K on service training. People return for people.',
        { cash: -250_000, quality: 6, morale: 6 },
        'The team learns every regular’s name and order.', 'Customers feel known. They come back.'),
    ],
  }),

  sc({
    id: 'cafe_subscription_abuse', biz: 'cafe', rounds: [6, 15], weeks: 3, needs: ['subscription'],
    title: 'Subscribers are coming in four times a day',
    story: ['“One a day” has become “one every two hours.”', 'Some are sharing a single account with friends.'],
    options: [
      o('Enforce one coffee a day', 'Add ID checks. Some subscribers will be upset.',
        { margin: 0.03, brand: -3, efficiency: -2 },
        'You add a QR check at the counter.', 'Sharing stops. A few angry posts appear.'),
      o('Raise the price to LKR 12,900', 'Keep it generous, charge more.',
        { price: 1.05, customers: 0.95 },
        'The new price goes live next month.', 'About one in ten subscribers cancel.'),
      o('Let it be, upsell food', 'Train baristas to sell a pastry with every refill.',
        { margin: 0.015, market: 1.04, morale: -2 },
        '“A croissant with that?”', 'Food sales climb. The coffee is still a loss.'),
      o('End the subscription', 'Go back to normal prices.',
        { price: 1.08, market: 0.92, clear: ['subscription'] },
        'You close the subscription with a thank-you note.', 'Revenue per customer goes up. Visits go down.'),
    ],
  }),

  sc({
    id: 'cafe_corporate', biz: 'cafe', rounds: [4, 13], weeks: 4,
    title: 'A bank wants coffee for 300 staff, every day',
    story: ['Their head office is five minutes away.', 'They want a 20% discount and delivery by 8:30 a.m.'],
    options: [
      o('Sign at 20% off', 'Big steady volume, smaller margin, early mornings.',
        { market: 1.25, price: 0.97, margin: -0.01, morale: -3, set: ['corporate'] },
        'Three hundred cups leave at 8:15 every morning.', 'Your team starts at 6 now.'),
      o('Sign and hire a team for it', 'LKR 40K a week for a dedicated crew.',
        { market: 1.25, price: 0.97, fixed: 40_000, set: ['corporate'] },
        'A new morning crew handles the bank order.', 'The café floor stays calm.'),
      o('Counter at full price', 'Fewer cups, better money. They might say no.',
        { market: 1.07, brand: 2 },
        'They accept for senior staff only. 120 cups a day.', 'Smaller, but profitable.'),
      o('Decline, stay focused', 'Protect the café experience.',
        { quality: 2, morale: 2 },
        'You decline politely.', 'Your team stays fresh for walk-in customers.'),
    ],
  }),

  sc({
    id: 'cafe_corporate_renewal', biz: 'cafe', rounds: [8, 15], weeks: 4, needs: ['corporate'],
    title: 'The bank wants to add four more branches',
    story: ['They love you. Now they want 1,200 cups a day across Colombo.', 'You would need a central kitchen.'],
    options: [
      o('Build a central kitchen', 'LKR 3M, most of it on loan. Brew Lane becomes a supplier.',
        { cash: -800_000, debt: 2_200_000, market: 1.35, capacity: 1.4, fixed: 100_000, assets: 2_000_000, efficiency: 4 },
        'A small production kitchen opens in Kirulapone.', 'Brew Lane now runs on two engines: café and corporate.'),
      o('Partner with a catering firm', 'They produce, you brand it. Lower margin, no risk.',
        { market: 1.2, margin: -0.02, quality: -2 },
        'A catering partner handles production.', 'The coffee is good, not quite Brew Lane good.'),
      o('Add one branch only', 'Grow carefully. LKR 40K a week extra.',
        { market: 1.08, fixed: 40_000, morale: 2 },
        'One more branch gets its 8:15 delivery.', 'Manageable growth.'),
      o('Raise the price for the expansion', 'Say yes only at 10% higher prices.',
        { market: 1.1, price: 1.03, brand: 2 },
        'They agree to a higher price for the new branches.', 'Less volume, healthier margin.'),
    ],
  }),

  sc({
    id: 'cafe_franchise', biz: 'cafe', rounds: [9, 14], weeks: 4, when: s => s.brand >= 50,
    title: 'An investor wants to franchise Brew Lane',
    story: ['Galle, Kandy and Negombo. He pays you a fee and a cut of sales.', 'He also wants to change the menu.'],
    options: [
      o('Franchise it', 'LKR 1.5M upfront, more reach, less control.',
        { cash: 1_500_000, market: 1.15, brand: 5, quality: -4, set: ['franchise'] },
        'Three Brew Lanes open outside Colombo.', 'Not all of them make coffee the way you do.'),
      o('Open your own second café', 'LKR 2.6M, mostly on loan. Full control.',
        { cash: -800_000, debt: 1_800_000, capacity: 1.45, market: 1.3, fixed: 90_000, assets: 2_000_000 },
        'Brew Lane Galle opens in a converted Dutch house.', 'Two cafés, two sets of problems.'),
      o('License only the beans', 'Sell Brew Lane roasted beans in supermarkets.',
        { cash: -300_000, market: 1.1, margin: 0.01, brand: 4 },
        'Brew Lane bags appear on supermarket shelves.', 'Your name travels without your rent.'),
      o('Say no and stay one perfect café', 'Focus, quality, and a happy team.',
        { quality: 5, brand: 3, morale: 5 },
        'You decline.', 'Brew Lane stays small, focused and very good.'),
    ],
  }),
]
