import { o, sc, n } from './kit'

// DEMO-ONLY scenarios. None of these ever appear in the official game, and the official
// game's scenarios never appear here, so practising the demo gives no advance knowledge.
export const DEMO = [
  // ── Brew Lane Café ──
  sc({
    id: 'demo_cafe_open', biz: 'cafe', rounds: [1, 1], weeks: 3,
    title: 'Your espresso machine just broke',
    story: ['Monday, 7:40 a.m. A loud bang, then silence.', 'The repair takes two weeks. Your morning regulars are already queuing.'],
    options: [
      o('Rent a machine', 'LKR 150K for two weeks. Business as usual.',
        { cash: -150_000, morale: 2 },
        'A rented machine arrives by lunchtime.', 'Nobody notices anything changed.'),
      o('Buy a better machine', 'LKR 900K. Faster, better coffee for years.',
        { cash: -900_000, quality: 7, efficiency: 4, assets: 600_000 },
        'A new twin-group machine goes in on Wednesday.', 'Shots pull faster. The coffee tastes richer.'),
      o('Make it “slow coffee” fortnight', 'Hand-brewed coffee only. Turn the problem into a story.',
        { customers: 0.9, brand: 5, quality: 2, boost: 0.1 },
        'A chalkboard: “Two weeks of slow coffee. Worth the wait.”', 'Some people leave. Some people love it.'),
      o('Close and refresh the café', 'LKR 300K. Paint, repairs, reopen with the fixed machine.',
        { cash: -300_000, customers: 0.8, brand: 4, quality: 3 },
        'Doors closed, paint rollers out.', 'Two weeks later, Brew Lane reopens looking new.'),
    ],
  }),
  sc({
    id: 'demo_cafe_food', biz: 'cafe', rounds: [2, 8], weeks: 3,
    title: 'Customers want food with their coffee',
    story: ['“Do you have anything to eat?” You hear it twenty times a day.'],
    options: [
      o('Make sandwiches in-house', 'LKR 20K a week for a kitchen helper.',
        { fixed: 20_000, market: 1.08, price: 1.03 },
        'Fresh sandwiches every morning.', 'The average bill goes up.'),
      o('Partner with a home baker', 'She supplies, you sell, you share the profit.',
        { market: 1.05, brand: 2 },
        'Banana bread and brownies from a home baker in Dehiwala.', 'They sell out by 3 p.m.'),
      o('Sri Lankan short eats', 'LKR 200K for a hot cabinet. Patties, rolls, cutlets.',
        { cash: -200_000, market: 1.07, brand: 4 },
        'Fish buns and Chinese rolls next to the flat whites.', 'Office workers start coming for tea time.'),
      o('Stay coffee only', 'Do one thing perfectly.',
        { quality: 3, morale: 2 },
        'You keep the menu simple.', 'The coffee stays the star.'),
    ],
  }),
  sc({
    id: 'demo_cafe_laptops', biz: 'cafe', rounds: [2, 8], weeks: 3,
    title: 'Laptop users stay five hours on one coffee',
    story: ['Every table is taken by 10 a.m.', 'New customers walk in, look around, and leave.'],
    options: [
      o('Two-hour Wi-Fi limit', 'Free up tables. Some regulars will grumble.',
        { customers: 1.04, brand: -2, efficiency: 3 },
        'Wi-Fi codes now last two hours.', 'Tables turn over faster.'),
      o('Minimum spend after 2 hours', 'Stay as long as you like. Order something every two hours.',
        { price: 1.03, brand: -1 },
        'A polite card on every table.', 'Most people order a second drink.'),
      o('Create a laptop zone', 'LKR 250K for a long bar with plugs at the back.',
        { cash: -250_000, capacity: 1.08, brand: 3 },
        'Laptops at the back, conversations at the front.', 'Everyone has a place.'),
      o('Let them stay', 'They are loyal and they bring friends.',
        { brand: 2, morale: 1, customers: 0.97 },
        'You leave it alone.', 'The café feels like a library. Some love that.'),
    ],
  }),
  sc({
    id: 'demo_cafe_books', biz: 'cafe', rounds: [2, 8], weeks: 3,
    title: 'The bookshop next door is closing',
    story: ['Forty years on the lane. Its owner is retiring.', 'Her loyal readers will need somewhere to go.'],
    options: [
      o('Add a book corner', 'LKR 150K for shelves and her best stock.',
        { cash: -150_000, brand: 5, market: 1.04 },
        'Second-hand books on a shelf by the window.', 'Her readers become your regulars.'),
      o('Host her farewell event', 'A reading night. LKR 60K.',
        { cash: -60_000, brand: 4, boost: 0.15 },
        'A packed farewell night with readings and coffee.', 'The lane remembers who hosted it.'),
      o('Ask the landlord about her space', 'Expansion talks. Nothing spent yet.',
        { morale: 1 },
        'You ask about the lease.', 'The landlord promises to call you first.'),
      o('Focus on your own customers', 'Not your business.',
        { efficiency: 2 },
        'You wish her well.', 'Life on the lane goes on.'),
    ],
  }),

  // ── Amma's Kitchen ──
  sc({
    id: 'demo_rest_open', biz: 'restaurant', rounds: [1, 1], weeks: 3,
    title: 'Your head cook quits on Friday night',
    story: ['The weekend is fully booked. Two family functions on Sunday.', 'He walked out after an argument with Amma.'],
    options: [
      o('Amma takes over the kitchen', 'Free, but she is 68 and it is a long weekend.',
        { quality: 4, morale: -5, capacity: 0.95 },
        'Amma ties her apron and runs the kitchen for three days.', 'The food is perfect. Amma is exhausted.'),
      o('Hire a temporary cook', 'LKR 25K a week until you find someone.',
        { fixed: 25_000, quality: -2 },
        'A temporary cook from a hotel agency.', 'The food is fine. Not quite Amma’s.'),
      o('Simplify the weekend menu', 'Only the ten dishes everyone can cook.',
        { efficiency: 5, quality: -1, brand: -1 },
        'A short weekend menu.', 'Service runs smoothly.'),
      o('Call him back and apologise', 'Fix the relationship. Costs a raise.',
        { fixed: 10_000, morale: 6 },
        'You visit his home on Saturday morning.', 'He is back by lunch, with a small raise.'),
    ],
  }),
  sc({
    id: 'demo_rest_radio', biz: 'restaurant', rounds: [2, 8], weeks: 3,
    title: 'A Kandy radio station wants a weekly cooking segment',
    story: ['Ten minutes every Sunday morning. No payment either way.'],
    options: [
      o('Amma does it live', 'Her voice, her recipes.',
        { brand: 6, boost: 0.15, morale: 2 },
        'Amma explains coconut sambol on air.', 'Callers ask where the restaurant is.'),
      o('Sponsor the whole show', 'LKR 200K for the season. Your name in every break.',
        { cash: -200_000, brand: 8, market: 1.04 },
        '“Brought to you by Amma’s Kitchen.”', 'The whole of Kandy hears your name.'),
      o('Give away a dinner each week', 'Listeners win a family meal.',
        { cash: -40_000, brand: 4, boost: 0.1 },
        'A family wins dinner every Sunday.', 'They bring their friends next time.'),
      o('Decline', 'The team is busy enough.',
        { morale: 2 },
        'You pass.', 'Sundays stay calm.'),
    ],
  }),
  sc({
    id: 'demo_rest_gas', biz: 'restaurant', rounds: [2, 8], weeks: 3,
    title: 'There’s a cooking gas shortage',
    story: ['Queues for gas cylinders all over Kandy.', 'You have three days of gas left.'],
    options: [
      o('Switch to firewood cooking', 'Old-style hearth. Smoky, slow, authentic.',
        { efficiency: -4, brand: 5, quality: 2 },
        'A wood hearth in the back yard.', '“Cooked on firewood” becomes a selling point.'),
      o('Buy induction cookers', 'LKR 400K. Electricity instead of gas, for good.',
        { cash: -400_000, efficiency: 4, assets: 250_000 },
        'Six induction cookers arrive.', 'Cleaner, faster, and no more queues.'),
      o('Pay double from a reseller', 'Keep cooking as normal. Costs more per plate.',
        { margin: -0.02 },
        'You pay a premium for cylinders.', 'The menu doesn’t change. The margin does.'),
      o('Cut to a short menu', 'Only dishes that need little cooking.',
        { customers: 0.93, efficiency: 3 },
        'A short gas-saving menu.', 'Fewer choices, still open.'),
    ],
  }),
  sc({
    id: 'demo_rest_critic', biz: 'restaurant', rounds: [2, 8], weeks: 3,
    title: 'A well-known food writer is coming this week',
    story: ['You don’t know which day. You don’t know what she looks like.'],
    options: [
      o('Treat every table like the critic’s', 'Extra staff all week. LKR 60K.',
        { cash: -60_000, quality: 4, brand: 4 },
        'Every guest gets the critic treatment.', 'Regulars notice the extra care too.'),
      o('Make a special tasting menu', 'Showcase Amma’s best dishes.',
        { brand: 5, price: 1.02, efficiency: -2 },
        'A seven-dish tasting menu appears.', 'It gets photographed a lot.'),
      o('Change nothing', 'Show her the real Amma’s.',
        { morale: 2, brand: 2 },
        'Business as usual.', 'She gets the honest experience.'),
      o('Invite her into the kitchen', 'Bold. Let her cook with Amma.',
        { brand: 7, boost: 0.1 },
        'Amma hands her a coconut scraper.', 'Her article opens with that moment.'),
    ],
  }),

  // ── Nexora ──
  sc({
    id: 'demo_tech_open', biz: 'tech', rounds: [1, 1], weeks: 3,
    title: 'A startup wants to pay you in shares, not cash',
    story: ['Three months of work for 5% of their company.', 'They say they’ll be worth billions. They also have no revenue.'],
    options: [
      o('Accept the shares', 'No cash for three months. Maybe a big payoff later.',
        { customers: 1.16, margin: -0.03, assets: 900_000, morale: 3, brand: 2 },
        'Your team starts building their app.', 'Busy, exciting, and unpaid.'),
      o('Half cash, half shares', 'A balanced deal.',
        { customers: 1.14, margin: -0.015, assets: 450_000, brand: 1 },
        'They agree to pay half in cash.', 'Some money in, some upside kept.'),
      o('Cash only', 'Full price or no deal.',
        { customers: 1.1, brand: 2 },
        'They agree to a smaller paid project.', 'Small, safe, paid.'),
      o('Decline politely', 'Keep the team for paying clients.',
        { efficiency: 2 },
        'You wish them luck.', 'The team stays on paid work.'),
    ],
  }),
  sc({
    id: 'demo_tech_side', biz: 'tech', rounds: [2, 8], weeks: 3,
    title: 'Your best developer is building a side project at work',
    story: ['A tool to help students find scholarships.', 'It’s good. It’s also on company time.'],
    options: [
      o('Make it a company project', 'Give her 20% of her time for it.',
        { capacity: 0.97, morale: 8, brand: 4 },
        'The project becomes “Nexora Labs”.', 'Other engineers start pitching ideas.'),
      o('Ask her to do it after hours', 'Fair rules for everyone.',
        { morale: -2, efficiency: 2 },
        'A clear policy goes out.', 'She keeps building it at night.'),
      o('Launch it under Nexora', 'LKR 200K to polish and release it.',
        { cash: -200_000, brand: 7, market: 1.03 },
        'The tool launches with Nexora’s name.', 'Students and universities share it.'),
      o('Ignore it', 'She delivers her work. Leave it alone.',
        { morale: 2 },
        'You say nothing.', 'Nothing changes.'),
    ],
  }),
  sc({
    id: 'demo_tech_late', biz: 'tech', rounds: [2, 8], weeks: 3,
    title: 'A client wants to pay six months late',
    story: ['They owe LKR 1.2 million. Their business is struggling.'],
    options: [
      o('Agree, with interest', 'Keep the client, wait for the money.',
        { cash: -250_000, brand: 3 },
        'You agree to a payment plan.', 'The client is grateful. Your cash is tighter.'),
      o('Pause work until they pay', 'Firm but fair.',
        { customers: 0.95, cash: 300_000 },
        'Work pauses. Part of the money arrives a week later.', 'The relationship cools.'),
      o('Take part in shares instead', 'Convert the debt into a stake.',
        { assets: 600_000, cash: -200_000 },
        'You become a small shareholder.', 'If they recover, so does your money.'),
      o('Hand it to a collection agency', 'Get most of it now, lose the client.',
        { cash: 600_000, customers: 0.93, brand: -2 },
        'An agency recovers most of the money.', 'You won’t hear from that client again.'),
    ],
  }),
  sc({
    id: 'demo_tech_web', biz: 'tech', rounds: [2, 8], weeks: 3,
    title: 'Your own website hasn’t been updated since 2019',
    story: ['You build websites for others. Yours says “Coming soon: AI”.'],
    options: [
      o('Rebuild it properly', 'Two engineers for two weeks.',
        { capacity: 0.97, brand: 6, market: 1.03 },
        'A new site with real case studies.', 'Enquiries start coming through it.'),
      o('Hire an agency', 'LKR 300K. Your team stays on clients.',
        { cash: -300_000, brand: 5 },
        'An agency builds it in three weeks.', 'It looks great.'),
      o('Just post case studies on LinkedIn', 'Free and quick.',
        { brand: 3 },
        'A weekly post about a real project.', 'Some of them get shared.'),
      o('Leave it', 'Clients come from referrals anyway.',
        { efficiency: 1 },
        'The website stays as it is.', 'Referrals keep coming.'),
    ],
  }),

  // ── Thread & Co. ──
  sc({
    id: 'demo_fash_open', biz: 'fashion', rounds: [1, 1], weeks: 3,
    title: 'Your new fabric is stuck at the port',
    story: ['Three weeks of delays. Your new collection was meant to launch Friday.'],
    options: [
      o('Pay to rush it through', 'LKR 300K in extra fees.',
        { cash: -300_000, boost: 0.15 },
        'The fabric clears in four days.', 'The collection launches only a week late.'),
      o('Buy local fabric instead', 'Different look, faster, “made fully in Sri Lanka”.',
        { margin: -0.01, brand: 5 },
        'You switch to handloom from Kurunegala.', 'The story becomes part of the collection.'),
      o('Delay the launch, build hype', 'A countdown on Instagram.',
        { brand: 3, boost: 0.2, customers: 0.95 },
        '“Coming soon” posts every day.', 'People wait, and talk.'),
      o('Sell remaining stock harder', 'Promote what you already have.',
        { cash: 200_000, brand: -1 },
        'A “last of the season” promotion.', 'The old stock moves.'),
    ],
  }),
  sc({
    id: 'demo_fash_trend', biz: 'fashion', rounds: [2, 8], weeks: 3,
    title: 'A TikTok trend wants a colour you don’t make',
    story: ['Everyone wants sage green this month.', 'You have none.'],
    options: [
      o('Rush a sage green line', 'LKR 400K for a quick run.',
        { cash: -400_000, boost: 0.3, brand: 3 },
        'Sage green pieces arrive in ten days.', 'They sell fast, while the trend lasts.'),
      o('Dye existing stock', 'LKR 100K to over-dye plain pieces.',
        { cash: -100_000, boost: 0.15, quality: -1 },
        'Plain shirts become sage.', 'Quick, cheap, not perfect.'),
      o('Ignore trends, stay classic', 'Your brand is timeless.',
        { brand: 2, quality: 2 },
        'You stick to your colours.', 'Loyal customers like that.'),
      o('Pre-orders only', 'Make only what people pay for in advance.',
        { cash: 150_000, efficiency: 3 },
        'Pre-orders open for a sage collection.', 'No waste, no unsold stock.'),
    ],
  }),
  sc({
    id: 'demo_fash_bulk', biz: 'fashion', rounds: [2, 8], weeks: 3,
    title: 'A company wants 300 shirts for staff, at 30% off',
    story: ['A bank’s anniversary event. They want them in three weeks.'],
    options: [
      o('Accept the order', 'LKR 600K of sales, small margin.',
        { cash: 300_000, morale: -2 },
        'Three hundred shirts, delivered on time.', 'The bank’s staff wear your label.'),
      o('Counter at 15% off', 'Better margin, might lose it.',
        { cash: 250_000, brand: 1 },
        'They agree at 20% off.', 'A fair deal for both.'),
      o('Accept and add your logo inside', 'Free advertising on 300 people.',
        { cash: 250_000, brand: 4 },
        'Your label on every collar.', 'Colleagues ask where the shirts are from.'),
      o('Decline', 'Keep production for the stores.',
        { quality: 2 },
        'You decline.', 'Stores stay fully stocked.'),
    ],
  }),
  sc({
    id: 'demo_fash_window', biz: 'fashion', rounds: [2, 8], weeks: 3,
    title: 'Your shop window hasn’t changed in three months',
    story: ['Mall shoppers walk past without looking.'],
    options: [
      o('Hire a window stylist', 'LKR 120K a month.',
        { fixed: 30_000, brand: 5, boost: 0.1 },
        'A new window every two weeks.', 'People stop to take photos.'),
      o('Let staff design it', 'A monthly team competition.',
        { morale: 6, brand: 3 },
        'The team builds a window from old fabric scraps.', 'It’s the most creative window in the mall.'),
      o('Put a screen in the window', 'LKR 350K for a video display.',
        { cash: -350_000, brand: 4, assets: 200_000 },
        'Your lookbook plays on a big screen.', 'It catches eyes from across the corridor.'),
      o('Keep it simple', 'Clean window, clear prices.',
        { efficiency: 2 },
        'You add a simple price sign.', 'Clear, if not exciting.'),
    ],
  }),

  // ── Ella Ridge ──
  sc({
    id: 'demo_hotel_open', biz: 'hotel', rounds: [1, 1], weeks: 3,
    title: 'A landslide has closed the road to Ella',
    story: ['Nobody can drive in for a week. Twelve bookings want refunds.'],
    options: [
      o('Refund everyone', 'LKR 400K back to guests. Goodwill kept.',
        { cash: -400_000, brand: 5 },
        'Full refunds, no questions.', 'Several guests rebook for next month.'),
      o('Offer free date changes', 'Keep the money, keep the guests.',
        { brand: 2 },
        'Every guest gets a free date change.', 'Most accept.'),
      o('Bring guests by train', 'Arrange train tickets and station pickups.',
        { cash: -150_000, brand: 6, quality: 2 },
        'Guests arrive by the scenic train.', 'They say it was the best part of the trip.'),
      o('Use the quiet week for repairs', 'Fix what guests complained about.',
        { cash: -250_000, quality: 5, customers: 0.85 },
        'A week of repairs while the road is closed.', 'The hotel reopens in better shape.'),
    ],
  }),
  sc({
    id: 'demo_hotel_vlogger', biz: 'hotel', rounds: [2, 8], weeks: 3,
    title: 'A travel vlogger asks for a free week',
    story: ['Two million subscribers. She will “definitely mention you”.'],
    options: [
      o('Free week, full experience', 'Room, meals and tours. LKR 200K.',
        { cash: -200_000, brand: 8, boost: 0.25 },
        'She films sunrise from your balcony.', 'Bookings jump the week the video goes live.'),
      o('Half price', 'A discount, not a gift.',
        { cash: -60_000, brand: 3 },
        'She stays two nights.', 'A short mention in her video.'),
      o('Free stay for a dedicated video', 'Only if the whole video is about Ella Ridge.',
        { cash: -150_000, brand: 6, boost: 0.15 },
        'A ten-minute video, just about you.', 'Steady bookings for months.'),
      o('Decline', 'Your guests are your marketing.',
        { quality: 2 },
        'You decline politely.', 'The rooms stay with paying guests.'),
    ],
  }),
  sc({
    id: 'demo_hotel_breakfast', biz: 'hotel', rounds: [2, 8], weeks: 3,
    title: 'Guests say breakfast is the same every day',
    story: ['“Great on day one. By day three, it’s boring.”'],
    options: [
      o('Rotate a weekly menu', 'Seven different breakfasts.',
        { quality: 4, efficiency: -2, brand: 2 },
        'String hoppers Monday, pancakes Tuesday…', 'Guests look forward to breakfast.'),
      o('Add a live hopper station', 'LKR 150K for a station and a cook.',
        { cash: -150_000, fixed: 8_000, quality: 5, brand: 3 },
        'Hoppers made fresh in front of guests.', 'It’s in every photo.'),
      o('Breakfast in the garden', 'Same food, better setting.',
        { brand: 3, quality: 2 },
        'Breakfast moves to the garden facing the valley.', 'Nobody complains about the menu now.'),
      o('Charge extra for premium breakfast', 'A paid upgrade.',
        { price: 1.02, quality: 1 },
        'A premium breakfast for LKR 2,500 extra.', 'About a third of guests take it.'),
    ],
  }),
  sc({
    id: 'demo_hotel_wifi', biz: 'hotel', rounds: [2, 8], weeks: 3,
    title: 'The Wi-Fi drops every evening',
    story: ['Remote workers check out early. Reviews mention it.'],
    options: [
      o('Fibre upgrade', 'LKR 350K and LKR 5K a week.',
        { cash: -350_000, fixed: 5_000, quality: 4, market: 1.03 },
        'Fibre is installed.', 'Remote workers start booking longer stays.'),
      o('Satellite internet', 'LKR 500K. Works even when lines go down.',
        { cash: -500_000, quality: 5, assets: 300_000 },
        'A dish on the roof.', 'The fastest internet in Ella.'),
      o('Market it as a feature', '“Evenings offline.”',
        { brand: 3, market: 0.98 },
        'A sign at reception: evenings are for stars, not screens.', 'Some guests love it.'),
      o('Router in each corridor', 'LKR 80K. Cheap improvement.',
        { cash: -80_000, quality: 2 },
        'Better routers in every corridor.', 'Better, not perfect.'),
    ],
  }),

  // ── Any business ──
  sc({
    id: 'demo_any_rain', biz: 'any', rounds: [2, 7], weeks: 3,
    title: 'Heavy rain all week',
    story: s => [`Streets flooded. Your ${n(s).guests} are staying home.`],
    options: [
      o('Rainy-day offer', 'A discount for anyone who comes in.',
        { boost: 0.15, price: 0.99 },
        'A “rainy day” deal goes up.', 'A few brave people come in.'),
      o('Bring it to them', 'Delivery or home service for the week.',
        { cash: -60_000, boost: 0.1, brand: 3 },
        'You take orders by phone and deliver.', 'People remember you came to them.'),
      o('Use the time to train the team', 'A training week.',
        { quality: 3, morale: 3 },
        'Quiet days become training days.', 'The team comes out sharper.'),
      o('Cut hours for the week', 'Save money while it’s quiet.',
        { fixedPct: 0.98, morale: 1 },
        'Shorter hours until the rain stops.', 'Lower costs, quiet week.'),
    ],
  }),
  sc({
    id: 'demo_any_unfair', biz: 'any', rounds: [2, 7], weeks: 3,
    title: 'A one-star review blames you for something that wasn’t your fault',
    story: ['A delivery driver was late. The review says your business is “a disgrace”.'],
    options: [
      o('Reply calmly with the facts', 'Polite and clear.',
        { brand: 3 },
        'You explain what happened, politely.', 'Readers take your side.'),
      o('Apologise and offer a gift', 'LKR 10K voucher.',
        { cash: -10_000, brand: 2 },
        'The customer gets a voucher.', 'They update the review to three stars.'),
      o('Ask happy customers for reviews', 'A sign at the counter.',
        { brand: 4 },
        'Ten new five-star reviews in a week.', 'The bad one sinks out of sight.'),
      o('Ignore it', 'One review doesn’t matter.',
        { brand: -1 },
        'You leave it.', 'It stays at the top for a while.'),
    ],
  }),
  sc({
    id: 'demo_any_payments', biz: 'any', rounds: [2, 7], weeks: 3,
    title: 'Customers want to pay by QR code',
    story: ['“Cash only? Seriously?”', 'Two customers left this morning because of it.'],
    options: [
      o('Add QR and card payments', 'LKR 60K setup, small fee per payment.',
        { cash: -60_000, margin: -0.01, market: 1.05 },
        'A QR stand on the counter.', 'Nobody walks away anymore.'),
      o('QR only, no cards', 'Lower fees.',
        { market: 1.03 },
        'A QR code for local bank apps.', 'Most customers are happy.'),
      o('Add an ATM nearby', 'Partner with a bank for an ATM outside.',
        { cash: -20_000, market: 1.02 },
        'An ATM outside your door.', 'Cash stays king, for now.'),
      o('Stay cash only', 'No fees at all.',
        { market: 0.98 },
        'Cash only, as always.', 'A few customers keep walking away.'),
    ],
  }),
  sc({
    id: 'demo_any_sale', biz: 'any', rounds: [3, 7], weeks: 3,
    title: 'A competitor announces a 50% off weekend',
    story: ['Posters everywhere. Your regulars are talking about it.'],
    options: [
      o('Match it', 'Half price for a weekend.',
        { boost: 0.2, margin: -0.01 },
        'You match the deal.', 'Busy weekend, thin profit.'),
      o('Add value, not discounts', 'A free extra with every purchase.',
        { boost: 0.1, brand: 3 },
        'Every customer gets a little extra.', 'People feel looked after.'),
      o('Run a loyalty weekend for regulars', 'Thank your best customers.',
        { brand: 4, morale: 2 },
        'Your regulars get a thank-you weekend.', 'They don’t go anywhere.'),
      o('Do nothing', 'It’s one weekend.',
        { customers: 0.97 },
        'You let them have their weekend.', 'Things are back to normal by Monday.'),
    ],
  }),
  sc({
    id: 'demo_any_idea', biz: 'any', rounds: [3, 7], weeks: 3,
    title: s => `A junior member of your ${n(s).team} has an idea`,
    story: ['She wants to try something new and asks for one month.'],
    options: [
      o('Give her a month and a budget', 'LKR 100K to test it.',
        { cash: -100_000, morale: 6, brand: 3, market: 1.02 },
        'She runs her experiment.', 'It works better than expected.'),
      o('Let her try with no budget', 'Free, motivating.',
        { morale: 4, brand: 1 },
        'She tries it on a shoestring.', 'Small results, big energy.'),
      o('Add it to next year’s plan', 'Not now.',
        { morale: -2, efficiency: 1 },
        'The idea goes into a folder.', 'She is a little disappointed.'),
      o('Run a team idea contest', 'Everyone pitches. Best idea wins LKR 50K.',
        { cash: -50_000, morale: 7, efficiency: 2 },
        'Ten ideas, one winner.', 'The whole team starts thinking like owners.'),
    ],
  }),
  sc({
    id: 'demo_any_photos', biz: 'any', rounds: [2, 7], weeks: 3,
    title: 'Your social media hasn’t posted in two months',
    story: s => [`Your last post is a blurry photo of the ${n(s).place}.`],
    options: [
      o('Hire a social media freelancer', 'LKR 15K a week.',
        { fixed: 15_000, brand: 6 },
        'Three good posts a week.', 'Followers start growing.'),
      o('The team posts daily', 'Free, real, behind the scenes.',
        { brand: 4, morale: 2 },
        'The team films short behind-the-scenes clips.', 'People like seeing the real faces.'),
      o('Run paid ads', 'LKR 150K for a month of ads.',
        { cash: -150_000, boost: 0.2, brand: 2 },
        'Ads run across the city.', 'A quick lift in visitors.'),
      o('Skip social media', 'Word of mouth is enough.',
        { efficiency: 1 },
        'You stay off social media.', 'Nothing changes.'),
    ],
  }),
  sc({
    id: 'demo_final', biz: 'any', rounds: [99, 99], final: true, weeks: 4,
    title: 'Last call: one big move for next month',
    story: ['Your last decision in the demo.', 'Pick the move you think will matter most.'],
    options: [
      o('Spend on growth', 'More reach, more customers.',
        { cashW: -0.6, market: 1.06, boost: 0.15 },
        'You go after new customers.', 'New faces start coming in.'),
      o('Tighten the business', 'Cut waste, protect profit.',
        { efficiency: 5, fixedPct: 0.97 },
        'You run a tight ship.', 'Profit per customer improves.'),
      o('Invest in the team', 'Bonuses and training.',
        { cashW: -0.3, morale: 10, quality: 4 },
        'The team gets a bonus and training.', 'They work like owners.'),
      o('Build the brand', 'A campaign people will remember.',
        { cashW: -0.5, brand: 7, boost: 0.15 },
        'A campaign launches.', 'People start talking about you.'),
    ],
  }),
]
