import { o, sc } from './kit'

// Thread & Co. — clothing brand, two mall stores in Colombo
export const FASHION = [
  sc({
    id: 'fash_open', biz: 'fashion', rounds: [1, 1], weeks: 4,
    title: 'LKR 3 million of last season’s stock. Nobody is buying it.',
    story: [
      'Racks of it in both stores and a storeroom full of boxes.',
      'The new collection can’t come in until the old one goes out.',
    ],
    options: [
      o('Huge clearance sale', '70% off everything old. Fast cash, cheaper-looking brand.',
        { cash: 1_500_000, assets: -1_600_000, boost: 0.35, brand: -4, morale: -2 },
        '“70% OFF” banners across both stores.', 'The racks empty in a week. People wonder if Thread & Co. is closing.'),
      o('Remake it into new designs', 'LKR 300K to rework old pieces into a limited collection.',
        { cash: -300_000, assets: -400_000, brand: 8, quality: 4, set: ['upcycle'] },
        'Old shirts become patchwork jackets. “Thread & Co. Reworked.”', 'Each piece is one of a kind. Fashion students love it.'),
      o('Donate it and tell the story', 'Give it to a charity. No cash, a lot of goodwill.',
        { assets: -1_200_000, brand: 7, morale: 4, boost: 0.1 },
        'Two vans of clothing go to families in need.', 'The story spreads, and so does goodwill for the brand.'),
      o('Sell it in bulk to an outlet', 'LKR 900K for all of it. Quiet and quick.',
        { cash: 900_000, assets: -1_400_000, efficiency: 4 },
        'A trader buys every box for a fraction of the price.', 'The storeroom is empty. Nobody even noticed.'),
    ],
  }),

  sc({
    id: 'fash_online', biz: 'fashion', rounds: [2, 9], weeks: 5, not: ['online'],
    title: 'Instagram brands are eating your lunch',
    story: ['They have no rent, just a phone and a delivery rider.', 'Your mall rent is LKR 1.4 million a month.'],
    options: [
      o('Launch a proper online store', 'LKR 600K for a website, photos and delivery.',
        { cash: -600_000, market: 1.25, brand: 4, set: ['online'] },
        'thread.lk goes live with a full lookbook.', 'Orders start arriving from Jaffna, Galle and Kurunegala.'),
      o('Close one store, go online-first', 'Save rent. Fewer people see you in person.',
        { fixedPct: 0.8, capacity: 0.8, market: 1.12, morale: -4, set: ['online'] },
        'The smaller store closes. The stock goes online.', 'Costs drop. Some loyal shoppers miss the store.'),
      o('Sell on online marketplaces', 'Big platforms, easy setup. They take 15%.',
        { market: 1.18, margin: -0.025, set: ['online'] },
        'Thread & Co. appears on the big marketplace apps.', 'Lots of orders, small profit on each.'),
      o('Make the stores worth visiting', 'LKR 800K on styling, music and a coffee bar.',
        { cash: -800_000, quality: 5, brand: 6, price: 1.04 },
        'A coffee bar, a stylist, and good music.', 'People stay longer and spend more.'),
    ],
  }),

  sc({
    id: 'fash_returns', biz: 'fashion', rounds: [4, 14], weeks: 4, needs: ['online'],
    title: 'One in four online orders comes back',
    story: ['“Too small.” “Different colour.” “Changed my mind.”', 'Every return costs you delivery both ways.'],
    options: [
      o('Free returns, always', 'Shoppers trust you more. Costs more.',
        { margin: -0.03, market: 1.1, brand: 4 },
        'Free returns, no questions asked.', 'People order more, and send more back.'),
      o('Charge for returns', 'LKR 350 per return. Fewer returns, some complaints.',
        { margin: 0.02, market: 0.96 },
        'Returns now cost LKR 350.', 'Returns halve. So does some goodwill.'),
      o('Build a size finder', 'LKR 400K for a fit quiz and real measurements.',
        { cash: -400_000, margin: 0.025, quality: 4, efficiency: 3 },
        'A size quiz on every product page.', 'Returns fall by half within a month.'),
      o('Exchange only, no refunds', 'Keep the money. Swap the size.',
        { margin: 0.015, brand: -2 },
        'Store credit and exchanges only.', 'Less cash out. A few angry reviews.'),
    ],
  }),

  sc({
    id: 'fash_influencer', biz: 'fashion', rounds: [2, 12], weeks: 4,
    title: 'A famous singer wants to design a collection with you',
    story: ['Two million followers. Her own sketches.', 'She wants 20% of sales from the collection.'],
    options: [
      o('Do the collaboration', 'LKR 800K production. Could be huge.',
        { cash: -800_000, boost: 0.5, brand: 10, market: 1.06, margin: -0.01 },
        'The collection drops at midnight.', 'The website crashes. Then it sells out.'),
      o('Do it, but limited edition', '500 pieces only. Lower risk, high hype.',
        { cash: -300_000, boost: 0.3, brand: 8, price: 1.03 },
        'Five hundred numbered pieces.', 'Gone in 40 minutes. People want more.'),
      o('Work with local micro-influencers', 'Twenty smaller creators. LKR 400K.',
        { cash: -400_000, brand: 6, market: 1.08 },
        'Twenty creators, twenty different styles.', 'Slower burn, wider reach.'),
      o('Decline, build your own voice', 'Keep the brand yours.',
        { brand: 2, morale: 3, quality: 2 },
        'You politely say no.', 'Your designers feel trusted.'),
    ],
  }),

  sc({
    id: 'fash_fabric', biz: 'fashion', rounds: [2, 12], weeks: 5,
    title: 'Your factory offers cheaper fabric',
    story: ['30% cheaper. Feels almost the same.', 'Almost.'],
    options: [
      o('Switch to save money', 'Better margin. Quality drops a little.',
        { margin: 0.06, quality: -7, brand: -3 },
        'The new fabric arrives.', 'Shirts look the same on the rack. After ten washes, they don’t.'),
      o('Use it for basics only', 'T-shirts cheap, signature pieces premium.',
        { margin: 0.03, quality: -2, price: 0.98, market: 1.05 },
        'A cheaper basics line, a premium signature line.', 'Two price points, two kinds of shopper.'),
      o('Go the other way: premium cotton', 'Costs more, sells for more.',
        { margin: -0.02, price: 1.1, quality: 8, brand: 5 },
        'Heavy Sri Lankan cotton, double stitching.', 'The clothes feel expensive, because they are.'),
      o('Keep the current fabric', 'No change.',
        { quality: 1 },
        'You keep everything as it is.', 'Consistency is a strategy too.'),
    ],
  }),

  sc({
    id: 'fash_sizes', biz: 'fashion', rounds: [3, 13], weeks: 4,
    title: '“Why don’t you make my size?”',
    story: ['Your sizes go from XS to L.', 'Hundreds of comments are asking for XL to 4XL.'],
    options: [
      o('Launch full inclusive sizing', 'LKR 500K for new patterns and stock.',
        { cash: -500_000, market: 1.14, brand: 7 },
        'XS to 4XL, every style.', 'A whole new group of shoppers discovers you.'),
      o('Add sizes to bestsellers only', 'LKR 200K. Test the demand.',
        { cash: -200_000, market: 1.06, brand: 3 },
        'Your top ten styles now come in XL and 2XL.', 'They sell faster than expected.'),
      o('Made-to-measure service', 'Custom fitting for a 20% premium.',
        { fixed: 25_000, price: 1.05, market: 1.04, quality: 4, brand: 4 },
        'A tailor in each store. Any size, any fit.', 'Slower, and very personal.'),
      o('Stay with current sizes', 'Keep stock simple.',
        { efficiency: 3, brand: -3 },
        'You keep your current range.', 'Simpler stock. Some shoppers feel ignored.'),
    ],
  }),

  sc({
    id: 'fash_leavers', biz: 'fashion', rounds: [3, 12], weeks: 4,
    title: 'Schools want custom batch hoodies for A/L leavers',
    story: ['Two hundred schools. Every batch wants its own design.', 'Orders are small, but there are many of them.'],
    options: [
      o('Go all in on batch merch', 'LKR 50K a week for a design team. Big new market.',
        { fixed: 50_000, market: 1.2, brand: 5, set: ['schools'] },
        '“Thread & Co. Batch Edition” launches with a design tool.', 'Forty schools order in the first month.'),
      o('Take orders over 100 pieces only', 'Bulk only, simple production.',
        { market: 1.08, efficiency: 3 },
        'Minimum order: 100 hoodies.', 'Fewer schools, easier production.'),
      o('Partner with student associations', 'Give 5% to student funds. Huge goodwill.',
        { market: 1.12, margin: -0.01, brand: 8 },
        'Every batch order supports a student fund.', 'Student leaders across the island share your name.'),
      o('Not your brand', 'Stay focused on fashion.',
        { brand: 1, quality: 1 },
        'You decline school orders.', 'The brand stays clean and focused.'),
    ],
  }),

  sc({
    id: 'fash_copy', biz: 'fashion', rounds: [4, 14], weeks: 3,
    title: 'A big chain copied your best-selling design',
    story: ['Same print. Same cut. Half the price.', 'It is on their front window.'],
    options: [
      o('Send a legal notice', 'LKR 300K in legal fees. Slow.',
        { cash: -300_000, brand: 3, morale: 2 },
        'Your lawyer sends a strongly worded letter.', 'They quietly take it off the window.'),
      o('Call it out publicly', 'Post side-by-side photos. Free and loud.',
        { brand: 8, boost: 0.25 },
        '“Spot the original.”', 'The post goes viral. Shoppers take your side.'),
      o('Release something new, fast', 'LKR 400K for a rushed new drop.',
        { cash: -400_000, brand: 5, quality: 3, boost: 0.2 },
        'Ten days later, a new design drops.', '“They copy, we create.”'),
      o('Ignore it', 'Copies prove you’re worth copying.',
        { morale: -1 },
        'You let it go.', 'Some shoppers buy the cheaper version.'),
    ],
  }),

  sc({
    id: 'fash_avurudu', biz: 'fashion', rounds: [3, 12], weeks: 4,
    title: 'Avurudu season is a month away',
    story: ['The biggest shopping season of the year.', 'Every brand is preparing a collection.'],
    options: [
      o('Big festive collection', 'LKR 1.2M on stock and campaign.',
        { cash: -1_200_000, assets: 600_000, boost: 0.55, brand: 5 },
        'Bright cottons, family matching sets, a TV-style campaign.', 'The stores are packed.'),
      o('Small capsule collection', 'LKR 500K. Less risk.',
        { cash: -500_000, assets: 250_000, boost: 0.3, brand: 3 },
        'Twelve festive pieces.', 'They sell steadily.'),
      o('Gift cards and bundles', 'Sell gifts, not just clothes.',
        { boost: 0.2, margin: 0.01, efficiency: 2 },
        'Gift boxes and family bundles.', 'Easy to buy, easy to give.'),
      o('Skip it and prepare for after', 'Launch fresh after the season when competitors are tired.',
        { boost: 0.05, efficiency: 3, morale: 2 },
        'You sit out the noise.', 'Your next launch comes when the market is quiet.'),
    ],
  }),

  sc({
    id: 'fash_export', biz: 'fashion', rounds: [6, 14], weeks: 5, when: s => s.quality >= 50,
    title: 'A boutique in London wants 2,000 pieces',
    story: ['Paid in pounds. Delivered in 60 days.', 'They want your designs with their label.'],
    options: [
      o('Take the order, their label', 'LKR 2.4M revenue. Your name stays hidden.',
        { cash: 1_300_000, efficiency: 3, morale: -2 },
        'Two thousand pieces leave Colombo port.', 'Good money. Nobody in London knows it’s yours.'),
      o('Only with your label', 'Smaller order, your brand goes global.',
        { cash: 600_000, brand: 7, market: 1.05 },
        'They agree to 800 pieces with your label.', '“Thread & Co. — Made in Sri Lanka.” In London.'),
      o('Set up an export line', 'LKR 1M to serve more overseas buyers.',
        { cash: -1_000_000, market: 1.22, fixed: 60_000, brand: 4, set: ['export'] },
        'You hire an export manager.', 'Enquiries arrive from London, Dubai and Sydney.'),
      o('Decline and focus on Sri Lanka', 'Protect your local stock and team.',
        { quality: 2, morale: 2 },
        'You decline the order.', 'All your capacity stays with local shoppers.'),
    ],
  }),

  sc({
    id: 'fash_commission', biz: 'fashion', rounds: [3, 13], weeks: 4,
    title: 'Your store staff want commission',
    story: ['They see other brands paying 5% on every sale.', 'Right now, they get a flat salary.'],
    options: [
      o('Pay 5% commission', 'Staff push harder to sell.',
        { margin: -0.025, morale: 9, market: 1.06 },
        'Commission starts on the 1st.', 'Suddenly, every shopper gets a smile and a suggestion.'),
      o('Team bonus on store targets', 'Shared target, shared reward.',
        { margin: -0.015, morale: 7, efficiency: 3 },
        'Each store gets a monthly target.', 'The team starts working together to hit it.'),
      o('Raise base salaries instead', 'LKR 30K more a week. No pushy selling.',
        { fixed: 30_000, morale: 6, quality: 3 },
        'Everyone gets a raise.', 'Calm stores, happy staff.'),
      o('No change', 'Keep costs as they are.',
        { morale: -6 },
        'You keep salaries as they are.', 'Two people start looking for other jobs.'),
    ],
  }),

  sc({
    id: 'fash_mall', biz: 'fashion', rounds: [5, 14], weeks: 4,
    title: 'The mall is raising rent by 20%',
    story: ['Your lease renews next month.', 'Foot traffic at the mall is down this year.'],
    options: [
      o('Pay it', 'Keep the best location.',
        { fixed: 40_000 },
        'You sign the new lease.', 'Same spot, higher bill.'),
      o('Negotiate a smaller unit', 'Half the space, 30% less rent.',
        { fixedPct: 0.9, capacity: 0.9, efficiency: 3 },
        'You move to a smaller unit on the same floor.', 'Tighter racks, better-chosen stock.'),
      o('Move to a street-front shop', 'LKR 800K to fit out. Cheaper rent, your own identity.',
        { cash: -800_000, fixedPct: 0.88, brand: 4, market: 0.97, assets: 500_000 },
        'A standalone shop on a busy road.', 'Your own front door and window.'),
      o('Pop-up stores instead', 'Move between events and markets.',
        { fixedPct: 0.84, capacity: 0.85, brand: 5, boost: 0.15 },
        'Thread & Co. pops up at markets, festivals and campuses.', 'Hard work, cheap rent, new faces.'),
    ],
  }),

  sc({
    id: 'fash_sustain', biz: 'fashion', rounds: [5, 14], weeks: 4,
    title: 'Young shoppers ask: is this sustainable?',
    story: ['Where is the cotton from? Who made it? Where does waste go?'],
    options: [
      o('Get eco-certified', 'LKR 700K and higher fabric costs.',
        { cash: -700_000, margin: -0.02, brand: 9, price: 1.05 },
        'A certified-sustainable label on every tag.', 'Shoppers are willing to pay a little more.'),
      o('Launch a take-back programme', 'Return old clothes for 15% off new ones.',
        { margin: -0.01, brand: 6, market: 1.06 },
        'A take-back bin at every store.', 'People come back to drop off old clothes, and buy new ones.'),
      o('Publish your factory story', 'LKR 150K for a short film about the people who make your clothes.',
        { cash: -150_000, brand: 5, morale: 4 },
        'Meet Kumari, who has stitched Thread & Co. for six years.', 'Shoppers feel connected to the clothes.'),
      o('Focus on price, not claims', 'Stay affordable and honest.',
        { market: 1.03, brand: -1 },
        'No new claims. Just fair prices.', 'Some shoppers care. Many don’t.'),
    ],
  }),
]
