import { o, sc } from './kit'

// Ella Ridge Hotel — 20-room boutique hotel, Ella
export const HOTEL = [
  sc({
    id: 'hotel_open', biz: 'hotel', rounds: [1, 1], weeks: 4,
    title: '“Amazing view. Tired hotel.”',
    story: [
      'That is the most common line in your reviews.',
      'Guests love the view of Ella Rock. They don’t love the leaking taps. Where do you start?',
    ],
    options: [
      o('Renovate every room', 'LKR 600K cash, LKR 2.4M loan. Rooms close in turns.',
        { cash: -600_000, debt: 2_400_000, customers: 0.75, quality: 12, price: 1.07, brand: 4, assets: 2_200_000 },
        'Builders work room by room. Guests share the hallway with paint cans.',
        'One by one, the rooms reopen looking brand new.'),
      o('Fix the top five complaints', 'LKR 800K for taps, Wi-Fi, beds, hot water and lobby.',
        { cash: -800_000, quality: 10, brand: 4, assets: 400_000 },
        'You read every bad review and fix what they mention.', 'The next reviews start with “Finally…”'),
      o('Cut rates by 4%', 'Fill rooms now. Lower profit per room.',
        { price: 0.96, boost: 0.3, market: 1.18, brand: 2 },
        'Your rates drop on every booking site.', 'Backpackers start booking. Rooms fill up.'),
      o('Become a digital-detox retreat', 'LKR 600K. No TVs, yoga at dawn, prices up 6%.',
        { cash: -600_000, brand: 6, price: 1.06, market: 0.96, set: ['retreat'] },
        '“Ella Ridge: Switch Off.” Phones in a box at check-in.',
        'Fewer guests, but the right ones, and they stay longer.'),
    ],
  }),

  sc({
    id: 'hotel_ota', biz: 'hotel', rounds: [2, 10], weeks: 4,
    title: 'Booking websites take 18% of every room',
    story: ['Ninety per cent of your guests book through them.', 'That is LKR 3,300 per room-night.'],
    options: [
      o('Push direct bookings', 'LKR 400K for a website with 10% off for booking direct.',
        { cash: -400_000, margin: 0.06, brand: 2, set: ['direct'] },
        'A new website with a “book direct, save 10%” button.', 'A third of guests now book direct.'),
      o('Pay for top placement', 'Extra 7% commission to appear first.',
        { margin: -0.035, market: 1.2, boost: 0.15 },
        'Ella Ridge appears at the top of search results.', 'Bookings jump. So does commission.'),
      o('Partner with travel agents', 'Contracted rooms at 25% off, guaranteed.',
        { price: 0.95, market: 1.15, margin: 0.01 },
        'Three agents add Ella Ridge to their tour packages.', 'Steady groups, lower rates.'),
      o('Leave it as it is', 'The sites bring guests. Accept the cost.',
        { efficiency: 1 },
        'Nothing changes.', 'The booking sites keep sending guests.'),
    ],
  }),

  sc({
    id: 'hotel_maldives', biz: 'hotel', rounds: [2, 9], weeks: 3,
    title: 'Your chef got a job offer from a Maldives resort',
    story: ['Three times his salary. Guests write about his breakfast in every review.'],
    options: [
      o('Match it partly', 'LKR 25K more a week.',
        { fixed: 25_000, quality: 4, morale: 4 },
        'He stays for now.', 'Breakfast is still the best in Ella.'),
      o('Give him a share of the restaurant', 'He runs it as his own. Costs margin.',
        { margin: -0.02, quality: 7, morale: 6, set: ['chefpartner'] },
        'He becomes a partner in the restaurant.', 'He starts inventing dishes.'),
      o('Let him go, promote the sous-chef', 'Cheaper. Breakfast changes.',
        { quality: -5, morale: 3, fixed: -10_000 },
        'A farewell dinner. The sous-chef steps up.', 'Breakfast is good, just not famous.'),
      o('Ask him to train a successor', 'LKR 200K bonus for a proper handover.',
        { cash: -200_000, quality: 2 },
        'He spends six weeks training his replacement.', 'The recipes stay.'),
    ],
  }),

  sc({
    id: 'hotel_experiences', biz: 'hotel', rounds: [2, 12], weeks: 4,
    title: 'Guests ask: “What is there to do?”',
    story: ['They arrive, take a photo, and leave the next morning.', 'Longer stays mean much more money.'],
    options: [
      o('Guided hikes and tea estate tours', 'LKR 20K a week for a guide.',
        { fixed: 20_000, market: 1.12, price: 1.04, brand: 4 },
        'Sunrise hikes to Little Adam’s Peak, afternoon tea tours.', 'Guests start staying three nights instead of one.'),
      o('Sri Lankan cooking classes', 'Run by your kitchen team.',
        { market: 1.08, price: 1.03, brand: 5, morale: 2 },
        'Guests learn to make hoppers and dhal.', 'It becomes the most-photographed part of their trip.'),
      o('Yoga and wellness', 'LKR 600K for a deck and an instructor.',
        { cash: -600_000, fixed: 15_000, price: 1.07, brand: 6, assets: 300_000 },
        'A yoga deck facing Ella Gap.', 'Wellness travellers start finding you.'),
      o('Partner with local operators', 'They run it, you take 10%.',
        { market: 1.06, margin: 0.01 },
        'Tuk-tuk tours, waterfall trips, train tickets.', 'Easy money, and happier guests.'),
    ],
  }),

  sc({
    id: 'hotel_offseason', biz: 'hotel', rounds: [4, 12], weeks: 6,
    title: 'Monsoon season. Bookings will halve.',
    story: ['Six slow weeks. The rooms still need cleaning. The loan still needs paying.'],
    options: [
      o('Discount for local travellers', 'Weekend packages for Colombo families at 30% off.',
        { boost: 0.25, price: 0.97, brand: 3 },
        '“Monsoon Weekends at Ella Ridge.”', 'Families from Colombo fill the weekends.'),
      o('Close and renovate', 'LKR 1.2M. Reopen better.',
        { cash: -1_200_000, customers: 0.6, quality: 10, assets: 800_000, morale: 2 },
        'The hotel closes for five weeks.', 'It reopens with new bathrooms and a fresh lobby.'),
      o('Host company retreats', 'Pitch to Colombo companies for team offsites.',
        { market: 1.12, margin: 0.01, set: ['corporate'] },
        'Three companies book offsites.', 'Weekdays that used to be empty are now full.'),
      o('Monthly stays for remote workers', 'Long-stay rooms at 40% off per night.',
        { price: 0.94, market: 1.1, efficiency: 4, set: ['nomads'] },
        'Remote workers move in for a month at a time.', 'Fewer check-ins, steadier income.'),
    ],
  }),

  sc({
    id: 'hotel_wedding', biz: 'hotel', rounds: [3, 13], weeks: 3,
    title: 'A couple wants their wedding at Ella Ridge',
    story: ['All 20 rooms for three nights. A ceremony on the lawn.', 'They offer LKR 1.8 million.'],
    options: [
      o('Accept, the full wedding', 'LKR 1.8M. Cancel other bookings.',
        { cash: 1_400_000, brand: 6, morale: -4, set: ['weddings'] },
        'Fairy lights on the lawn, 80 guests, one very happy couple.', 'The photos are everywhere.'),
      o('Accept, but keep some rooms', '12 rooms only. LKR 1M.',
        { cash: 800_000, brand: 4, set: ['weddings'] },
        'A smaller wedding, a few other guests.', 'Everyone gets a good stay.'),
      o('Price it at LKR 2.5M', 'They may walk away.',
        { cash: 1_100_000, brand: 2 },
        'They negotiate. You settle at LKR 2.2M with fewer rooms.', 'A profitable weekend.'),
      o('Decline, protect regular guests', 'Keep your reviews safe.',
        { quality: 2, morale: 2 },
        'You recommend a bigger venue.', 'A quiet weekend, as planned.'),
    ],
  }),

  sc({
    id: 'hotel_weddings_more', biz: 'hotel', rounds: [6, 15], weeks: 4, needs: ['weddings'],
    title: 'Wedding planners want to make you a venue',
    story: ['After the photos went viral, three planners called.', 'Weddings could fill your weekends all year.'],
    options: [
      o('Build a wedding pavilion', 'LKR 2.5M, mostly loan.',
        { cash: -700_000, debt: 1_800_000, market: 1.2, price: 1.04, assets: 1_800_000, brand: 4 },
        'A glass pavilion on the edge of the hill.', 'Weekends are booked a year ahead.'),
      o('One wedding a month', 'Balance weddings and regular guests.',
        { market: 1.1, brand: 3 },
        'One wedding a month.', 'Good money, guests still welcome.'),
      o('Partner with a planner', 'They sell, decorate and manage. You take 70%.',
        { market: 1.14, margin: -0.01 },
        'A planner handles everything.', 'Easy money, less control.'),
      o('Stop weddings', 'Focus on travellers and reviews.',
        { quality: 3, clear: ['weddings'] },
        'No more weddings.', 'Quiet weekends, perfect reviews.'),
    ],
  }),

  sc({
    id: 'hotel_solar', biz: 'hotel', rounds: [3, 13], weeks: 4,
    title: 'Your electricity bill is LKR 280,000 a month',
    story: ['Hot water, kitchen, air conditioning in some rooms.', 'Rates went up again this year.'],
    options: [
      o('Install solar panels', 'LKR 2.5M, part loan. Bills drop by two thirds.',
        { cash: -900_000, debt: 1_600_000, fixed: -45_000, assets: 1_800_000, brand: 3 },
        'Panels go up on the roof.', 'The meter runs backwards at noon.'),
      o('Solar water heaters only', 'LKR 700K. Cuts the biggest cost.',
        { cash: -700_000, fixed: -20_000, assets: 500_000 },
        'Solar heaters on the roof.', 'Hot showers, smaller bills.'),
      o('Energy-saving rules', 'Key-card power, LED bulbs. LKR 150K.',
        { cash: -150_000, fixed: -12_000, efficiency: 3, quality: -1 },
        'Lights turn off when guests leave.', 'Bills fall. A few guests find it annoying.'),
      o('Add an eco surcharge', 'LKR 500 per night, explained clearly.',
        { price: 1.03, brand: -1 },
        'A small eco fee on every booking.', 'Most guests don’t mind.'),
    ],
  }),

  sc({
    id: 'hotel_bedbugs', biz: 'hotel', rounds: [3, 14], weeks: 3,
    title: 'A guest posted photos of bedbugs',
    story: ['Room 7. Twelve thousand views overnight.', 'Two upcoming guests have already cancelled.'],
    options: [
      o('Close the room, treat everything, apologise', 'LKR 600K. Full transparency.',
        { cash: -600_000, quality: 6, brand: 2, customers: 0.9 },
        'Every room is treated. Every mattress is replaced.', 'You reply to the post with photos of the fix.'),
      o('Refund the guest and reply privately', 'LKR 50K. Quiet fix.',
        { cash: -50_000, brand: -6, quality: 2 },
        'A private apology and a refund.', 'The post stays up.'),
      o('Invite the guest back for free', 'Show them the fixed hotel. LKR 200K.',
        { cash: -200_000, brand: 5, quality: 4 },
        'The guest comes back and posts again.', '“They fixed everything. Credit where it’s due.”'),
      o('Hire a hygiene certification firm', 'LKR 900K. A certificate on every booking page.',
        { cash: -900_000, quality: 8, brand: 6, assets: 200_000 },
        'An independent firm certifies the hotel.', '“Certified clean” goes on every listing.'),
    ],
  }),

  sc({
    id: 'hotel_tour_operator', biz: 'hotel', rounds: [4, 13], weeks: 5,
    title: 'A European tour company wants 60% of your rooms',
    story: ['Guaranteed for a year, paid monthly.', 'At 35% below your normal rate.'],
    options: [
      o('Sign the full deal', 'Guaranteed income. Less room for higher-paying guests.',
        { market: 1.3, price: 0.88, efficiency: 4, set: ['touroperator'] },
        'Tour buses arrive every Tuesday and Saturday.', 'The hotel is full. The average rate falls.'),
      o('Offer 30% of rooms', 'Half the deal, half the discount risk.',
        { market: 1.14, price: 0.95 },
        'They take six rooms a night.', 'A steady base. Room left for walk-ins.'),
      o('Counter at 20% below', 'They may walk away.',
        { market: 1.08, price: 0.98, brand: 1 },
        'They agree to fewer rooms at your price.', 'A smaller, better deal.'),
      o('Decline', 'Keep full control of rates.',
        { brand: 2, morale: 1 },
        'You turn the deal down.', 'Every room still sells at full price, when it sells.'),
    ],
  }),

  sc({
    id: 'hotel_restaurant', biz: 'hotel', rounds: [3, 13], weeks: 4,
    title: 'Should non-guests be able to eat at your restaurant?',
    story: ['Your terrace has the best sunset view in Ella.', 'It is empty most evenings.'],
    options: [
      o('Open a sunset terrace bar', 'LKR 800K and LKR 30K a week.',
        { cash: -800_000, fixed: 30_000, market: 1.12, brand: 6, assets: 400_000 },
        '“Sunset at the Ridge” opens at 5 p.m. daily.', 'Travellers from other hotels walk up for dinner.'),
      o('Open for dinner only, set menu', 'Simple, high quality.',
        { market: 1.06, quality: 2, brand: 3 },
        'A five-course dinner for 20 people a night.', 'Booked out most evenings.'),
      o('Host weekly events', 'Live music Fridays.',
        { fixed: 12_000, boost: 0.2, brand: 4 },
        'Friday nights: music, lanterns, a full terrace.', 'Ella starts talking about Fridays at the Ridge.'),
      o('Keep it for guests', 'Peace and quiet.',
        { quality: 2 },
        'The terrace stays for guests only.', 'Guests love the calm.'),
    ],
  }),

  sc({
    id: 'hotel_cabins', biz: 'hotel', rounds: [8, 14], weeks: 5, when: s => s.customers > s.capacity * 0.6,
    title: 'The land next door is for sale',
    story: ['Enough space for eight cabins.', 'Your rooms are full more nights than ever.'],
    options: [
      o('Build eight luxury cabins', 'LKR 1.5M cash, LKR 4M loan.',
        { cash: -1_500_000, debt: 4_000_000, capacity: 1.4, market: 1.25, price: 1.05, fixed: 120_000, assets: 4_500_000 },
        'Eight wooden cabins with glass walls facing the valley.', 'They become the most-booked rooms in Ella.'),
      o('Build four simple cabins', 'LKR 2M total. Lower risk.',
        { cash: -700_000, debt: 1_300_000, capacity: 1.2, market: 1.1, fixed: 50_000, assets: 1_600_000 },
        'Four cosy cabins under the trees.', 'Steady extra income.'),
      o('Buy the land, build later', 'LKR 2M on land only.',
        { cash: -1_000_000, debt: 1_000_000, assets: 2_200_000 },
        'You buy the land and plant a garden.', 'An asset that waits for the right time.'),
      o('Pass', 'Focus on the 20 rooms you have.',
        { quality: 3, efficiency: 2 },
        'You let it go.', 'Every effort goes into the rooms you have.'),
    ],
  }),

  sc({
    id: 'hotel_insta', biz: 'hotel', rounds: [3, 13], weeks: 4,
    title: 'Your view could be famous',
    story: ['Hotels in Ella with an infinity pool or a sky swing get booked months ahead.'],
    options: [
      o('Build an infinity pool', 'LKR 1.2M cash, LKR 2.3M loan.',
        { cash: -1_200_000, debt: 2_300_000, brand: 9, price: 1.06, market: 1.08, assets: 2_800_000, fixed: 15_000 },
        'An infinity pool at the edge of the hill.', 'Every guest posts the same photo. It works.'),
      o('A photo deck and a swing', 'LKR 400K.',
        { cash: -400_000, brand: 7, boost: 0.2, assets: 200_000 },
        'A wooden deck and a swing over the valley.', 'It goes viral on a Tuesday.'),
      o('Hire a photographer for your listings', 'LKR 150K for professional photos.',
        { cash: -150_000, brand: 4, market: 1.05 },
        'New photos at sunrise, sunset and in the mist.', 'Your listing finally looks as good as the place.'),
      o('Keep it natural', 'Market the quiet and the view.',
        { brand: 2, quality: 1 },
        '“No pool. No swing. Just the mountains.”', 'A certain kind of traveller loves it.'),
    ],
  }),

  sc({
    id: 'hotel_retreat_followup', biz: 'hotel', rounds: [4, 14], weeks: 4, needs: ['retreat'],
    title: 'A wellness magazine wants to feature you',
    story: ['“Asia’s ten best digital-detox retreats.”', 'They want you to host their editor for a week.'],
    options: [
      o('Host her, all inclusive', 'LKR 250K.',
        { cash: -250_000, brand: 10, market: 1.1, price: 1.03 },
        'The editor stays a week and writes three pages.', 'International bookings follow.'),
      o('Launch week-long programmes', 'LKR 600K for a yoga teacher and ayurveda partner.',
        { cash: -600_000, fixed: 20_000, price: 1.1, market: 1.06, brand: 6 },
        'Seven-day detox programmes, fully planned.', 'Guests stay longer and pay more.'),
      o('Stay small and exclusive', 'Raise prices, cap guests.',
        { price: 1.12, market: 0.94, brand: 4 },
        'A waiting list appears.', 'Fewer guests, higher rates.'),
      o('Mix detox and regular guests', 'Keep your options open.',
        { market: 1.08, brand: -2, clear: ['retreat'] },
        'Detox for some, Wi-Fi for others.', 'More guests, a less clear story.'),
    ],
  }),
]
