import { o, sc } from './kit'

// Amma's Kitchen — Kandy
export const RESTAURANT = [
  sc({
    id: 'rest_open', biz: 'restaurant', rounds: [1, 1], weeks: 4,
    title: 'Young people walk past every day. Nobody comes in.',
    story: [
      'The regulars are loyal, but they are getting older.',
      'Students from the university walk past to the burger place. What is Amma’s Kitchen going to be?',
    ],
    options: [
      o('Modernise the menu', 'Rice bowls, kottu fusion, iced drinks. LKR 500K. Amma is not happy.',
        { cash: -500_000, market: 1.16, brand: 5, quality: 1, morale: -3, set: ['fusion'] },
        'Devilled-chicken rice bowls and iced faluda join the menu.',
        'Students start trying it. Amma refuses to cook the new dishes.'),
      o('Sell the heritage', '“Amma’s original recipes since 2004.” LKR 300K, prices up 5%.',
        { cash: -300_000, brand: 7, price: 1.05, quality: 3, set: ['heritage'] },
        'Old family photos go on the walls. Every dish gets its story on the menu.',
        'Tourists and food writers start paying attention.'),
      o('Go delivery-first', 'Join the apps and set up a delivery counter. Apps take 25%.',
        { market: 1.25, margin: -0.03, set: ['delivery'] },
        'Amma’s Kitchen goes live on the delivery apps.',
        'Rice packets leave on bikes all evening.'),
      o('Sell lunch packets to offices', 'Cheap, fast, high volume. Prices down 5%.',
        { market: 1.2, price: 0.95, efficiency: 6, set: ['lunchpacks'] },
        'By 11:30 a.m., 200 lunch packets are wrapped and ready.',
        'Volume is up. Each packet earns very little.'),
    ],
  }),

  sc({
    id: 'rest_amma', biz: 'restaurant', rounds: [2, 9], weeks: 3,
    title: 'Amma wants to cook every dish herself. She is 68.',
    story: ['The food is famous because of her hands.', 'She is getting tired, and the kitchen slows down when she rests.'],
    options: [
      o('Let her cook', 'Quality stays perfect. You can only serve so many plates.',
        { quality: 6, capacity: 0.9, morale: 3 },
        'Amma stays at the stove.', 'Every plate is perfect. On busy nights, people wait.'),
      o('Turn her recipes into a system', 'LKR 200K to write and train every recipe.',
        { cash: -200_000, efficiency: 8, quality: 2, capacity: 1.1, set: ['recipes'] },
        'Amma teaches, you write everything down. Grams, minutes, temperatures.',
        'The kitchen can now run without her.'),
      o('Make her the face of the brand', 'Short videos of Amma cooking. LKR 150K.',
        { cash: -150_000, brand: 6, boost: 0.3 },
        '“Amma explains why you never rush a fish curry.” 600K views.',
        'People come in asking to meet her.'),
      o('Hire a professional head chef', 'LKR 40K a week. Amma feels replaced.',
        { fixed: 40_000, quality: 5, capacity: 1.2, efficiency: 4, morale: -6 },
        'A hotel-trained chef joins the kitchen.', 'Faster service. A tense kitchen.'),
    ],
  }),

  sc({
    id: 'rest_tourists', biz: 'restaurant', rounds: [2, 12], weeks: 4,
    title: 'Tourists can’t find you',
    story: ['Kandy is full of travellers. Your Google listing has three photos and a wrong phone number.'],
    options: [
      o('Fix the online basics', 'LKR 100K for photos, an English menu and Google Maps.',
        { cash: -100_000, market: 1.12, brand: 4 },
        'Proper photos, an English menu, the right phone number.', 'The first backpackers walk in by Friday.'),
      o('Pay tuk-tuk drivers to bring tourists', '10% commission per table.',
        { market: 1.16, margin: -0.02 },
        'Drivers start recommending “real Sri Lankan food at Amma’s.”', 'Busier tables, smaller margins.'),
      o('Run cooking classes for tourists', 'LKR 15K a week. Teach them Amma’s recipes.',
        { fixed: 15_000, market: 1.06, price: 1.03, brand: 5, set: ['classes'] },
        'Six tourists in aprons learn to make pol sambol.', 'They post it everywhere.'),
      o('Stay focused on locals', 'Put the money into the regulars instead.',
        { cash: -100_000, quality: 3, morale: 3 },
        'You start a Sunday family special for regulars.', 'The regulars feel looked after.'),
    ],
  }),

  sc({
    id: 'rest_wedding', biz: 'restaurant', rounds: [3, 12], weeks: 3,
    title: 'A wedding for 400 guests wants your food — in two weeks',
    story: ['The bride grew up eating at Amma’s. The fee is LKR 1.2 million.', 'Your kitchen usually serves 160 people a day.'],
    options: [
      o('Accept, all hands on deck', 'LKR 1.2M. The restaurant closes for two days.',
        { cash: 1_200_000, morale: -8, quality: -2, customers: 0.92, brand: 4, set: ['catering'] },
        'Forty hours of cooking. Four hundred happy guests.', 'The team is exhausted but proud.'),
      o('Accept and hire temporary cooks', 'LKR 700K after hiring help. Restaurant stays open.',
        { cash: 700_000, brand: 4, set: ['catering'] },
        'Six temporary cooks join for the week.', 'The wedding goes well. The restaurant keeps running.'),
      o('Offer a smaller menu for 200', 'LKR 500K, less strain.',
        { cash: 500_000, brand: 2, morale: -2 },
        'They agree to 200 guests and a buffet.', 'A smaller job, done well.'),
      o('Decline politely', 'Protect the regular service.',
        { morale: 3, quality: 2 },
        'You recommend a caterer and wish them well.', 'The kitchen stays calm.'),
    ],
  }),

  sc({
    id: 'rest_catering_wave', biz: 'restaurant', rounds: [5, 15], weeks: 4, needs: ['catering'],
    title: 'After the wedding, the phone won’t stop ringing',
    story: ['Almsgivings, office parties, birthdays.', 'Catering could become a business of its own.'],
    options: [
      o('Launch a catering division', 'LKR 1.5M for a van and equipment, LKR 70K a week.',
        { cash: -700_000, debt: 800_000, market: 1.3, capacity: 1.3, fixed: 70_000, assets: 1_000_000 },
        'A white van with “Amma’s Kitchen Catering” on the side.', 'Weekends are booked a month ahead.'),
      o('Take only big events', 'Higher price, fewer jobs.',
        { market: 1.1, price: 1.04, brand: 3 },
        'You take only events over 150 guests.', 'Fewer jobs, better money.'),
      o('Partner with a wedding planner', 'They bring clients and take 15%.',
        { market: 1.15, margin: -0.015, brand: 2 },
        'A wedding planner adds you to her list.', 'Steady bookings without marketing.'),
      o('Say no to catering', 'Keep the kitchen focused on the restaurant.',
        { quality: 3, morale: 4, clear: ['catering'] },
        'You stop taking catering orders.', 'The restaurant gets your full attention.'),
    ],
  }),

  sc({
    id: 'rest_inspection', biz: 'restaurant', rounds: [3, 13], weeks: 3,
    title: 'A health inspector found problems in the kitchen',
    story: ['Old drains, a cracked floor, and a fridge that runs warm.', 'You have 30 days to fix them.'],
    options: [
      o('Renovate the whole kitchen', 'LKR 1.5M, half on loan. Faster and cleaner for years.',
        { cash: -700_000, debt: 800_000, quality: 10, efficiency: 8, assets: 900_000 },
        'New floor, new drains, new fridges.', 'The kitchen runs faster than it ever has.'),
      o('Fix only what was flagged', 'LKR 300K. Pass the inspection.',
        { cash: -300_000, quality: 3 },
        'The problems are fixed in a week.', 'You pass. Everything else is still old.'),
      o('Close for a week and build an open kitchen', 'LKR 900K. Let diners see the cooking.',
        { cash: -900_000, customers: 0.82, brand: 7, quality: 7, assets: 500_000 },
        'A glass wall now shows the kitchen to the dining hall.', 'Diners love watching the hoppers being made.'),
      o('Ask for more time', 'Free for now, but the risk stays.',
        { morale: -2, quality: -2, brand: -2 },
        'You ask for a 60-day extension.', 'It is granted. The fridge is still warm.'),
    ],
  }),

  sc({
    id: 'rest_rice', biz: 'restaurant', rounds: [2, 13], weeks: 4,
    title: 'Rice and coconut prices are up 25%',
    story: ['Bad monsoon. Every plate of rice and curry now costs more to make.'],
    options: [
      o('Absorb it', 'Keep prices, lose margin.',
        { margin: -0.025, brand: 3 },
        'Prices stay the same.', 'Diners are grateful. Your profit is not.'),
      o('Raise prices by 6%', 'Protect your margin.',
        { price: 1.06, brand: -2 },
        'A new menu with new prices.', 'Some regulars start coming every other week.'),
      o('Buy direct from farmers', 'LKR 300K deposit for a farm in Matale. Cheaper in the long run.',
        { cash: -300_000, margin: 0.02, quality: 3, brand: 3 },
        'You sign with a family farm in Matale.', '“Farm to plate” becomes part of the story.'),
      o('Redesign the menu', 'Fewer rice-heavy dishes, more vegetables and roti.',
        { margin: 0.01, efficiency: 4, quality: -2 },
        'The new menu leans on kottu, roti and vegetable curries.', 'Cheaper to make, a little less loved.'),
    ],
  }),

  sc({
    id: 'rest_lunch_park', biz: 'restaurant', rounds: [4, 14], needs: ['lunchpacks'], weeks: 4,
    title: 'An office park wants 500 lunch packets a day',
    story: ['An IT park in Digana. Two-year contract.', 'They pay 45 days after delivery.'],
    options: [
      o('Sign for all 500', 'Huge volume. You must hire and wait for payment.',
        { market: 1.3, capacity: 1.25, fixed: 55_000, cashW: -1.2, efficiency: 3 },
        'Five hundred packets every morning by 11:45.', 'Cash is tight while you wait for their first payment.'),
      o('Sign for 250', 'Half the order, half the risk.',
        { market: 1.14, fixed: 25_000, cashW: -0.5 },
        'Two hundred and fifty packets a day.', 'Manageable, profitable, steady.'),
      o('Ask for payment weekly', 'Better cash flow. They may offer less.',
        { market: 1.1, margin: 0.01 },
        'They agree to weekly payment for 200 packets.', 'Smaller deal, money in the bank every Friday.'),
      o('Walk away from packets', 'Move back toward dine-in.',
        { price: 1.08, market: 0.94, quality: 3, clear: ['lunchpacks'] },
        'You stop the lunch packet business.', 'Fewer plates, better plates.'),
    ],
  }),

  sc({
    id: 'rest_delivery_fee', biz: 'restaurant', rounds: [4, 14], needs: ['delivery'], weeks: 4,
    title: 'Delivery orders are up. Profit isn’t.',
    story: ['The apps take 25%. Packaging costs LKR 60 an order.', 'Half your sales now leave on a bike.'],
    options: [
      o('Delivery-only menu at higher prices', 'Price delivery 12% above dine-in.',
        { price: 1.04, customers: 0.96, margin: 0.01 },
        'Delivery prices go up.', 'Orders dip slightly. Each one is worth more.'),
      o('Build your own delivery', 'Two riders and a hotline. LKR 30K a week.',
        { fixed: 30_000, margin: 0.04, market: 0.97, set: ['ownorders'] },
        'Two riders in Amma’s Kitchen T-shirts.', 'You keep the full price on every order.'),
      o('Cheaper eco packaging', 'LKR 200K for leaf packaging. Better story.',
        { cash: -200_000, margin: 0.01, brand: 5 },
        'Food arrives wrapped in banana leaf.', 'People photograph it before they eat.'),
      o('Accept it as marketing', 'The apps find you new customers. Keep going.',
        { brand: 2, market: 1.05 },
        'You leave everything as it is.', 'The apps keep bringing in new faces.'),
    ],
  }),

  sc({
    id: 'rest_cousin', biz: 'restaurant', rounds: [3, 12], weeks: 3,
    title: 'Your cousin wants to be the manager',
    story: ['He has no restaurant experience. He is family.', 'Amma thinks it is a wonderful idea.'],
    options: [
      o('Hire him', 'Family harmony. He learns on the job.',
        { fixed: 30_000, morale: 2, efficiency: -4 },
        'He starts on Monday.', 'He is enthusiastic, and often wrong.'),
      o('Hire him on probation with targets', 'Three months to prove himself.',
        { fixed: 30_000, efficiency: 2, morale: -1 },
        'Clear targets on paper, signed by both of you.', 'He works harder than you expected.'),
      o('Hire a professional manager', 'LKR 45K a week. The family is upset.',
        { fixed: 45_000, efficiency: 7, quality: 2, morale: -4 },
        'A manager from a hotel chain joins.', 'Things run smoothly. Family lunches are tense.'),
      o('Give him a small project', 'He runs the Sunday special. You stay in charge.',
        { boost: 0.08, morale: 2 },
        'He gets the Sunday family special.', 'It is his to win or lose.'),
    ],
  }),

  sc({
    id: 'rest_menu', biz: 'restaurant', rounds: [3, 13], weeks: 4,
    title: 'Your menu has 74 dishes',
    story: ['The kitchen stocks ingredients for all of them.', 'Twelve dishes make 80% of sales.'],
    options: [
      o('Cut to 20 dishes', 'Faster, cheaper, fresher. Some regulars lose a favourite.',
        { efficiency: 10, margin: 0.03, quality: 4, market: 0.95 },
        'Seventy-four dishes become twenty.', 'Food comes out faster and tastes fresher.'),
      o('Cut to 40 dishes', 'A safer middle ground.',
        { efficiency: 5, margin: 0.015, quality: 2 },
        'You remove the dishes nobody orders.', 'The kitchen breathes easier.'),
      o('Keep all 74, add specials', 'Variety is what regulars love.',
        { market: 1.04, efficiency: -3, brand: 2 },
        'A daily specials board joins the 74 dishes.', 'Choice is up. So is waste.'),
      o('Rotate a weekly menu', 'A new menu every week. Creative and unpredictable.',
        { brand: 6, efficiency: 2, boost: 0.15, morale: 3 },
        '“This week at Amma’s” goes up every Monday.', 'Regulars come back to see what’s new.'),
    ],
  }),

  sc({
    id: 'rest_perahera', biz: 'restaurant', rounds: [4, 12], weeks: 3,
    title: 'The Esala Perahera brings 100,000 visitors to Kandy',
    story: ['Ten days of processions. The city is packed.', 'Every restaurant is preparing.'],
    options: [
      o('Open 18 hours a day', 'Maximise the rush. The team will be exhausted.',
        { boost: 0.45, morale: -8, quality: -2 },
        'Doors open at 6 a.m. and close at midnight.', 'The tills never stop. Neither does the team.'),
      o('Rent a roadside stall on the route', 'LKR 300K for a stall where crowds stand.',
        { cash: -300_000, boost: 0.4, brand: 6 },
        'An Amma’s Kitchen stall right on the procession route.', 'Thousands of people taste your food for the first time.'),
      o('Perahera special set menu', 'One fixed menu at a premium price.',
        { boost: 0.25, price: 1.03, efficiency: 4 },
        'A Perahera set menu at LKR 1,450.', 'Fast to serve, easy to sell.'),
      o('Keep things normal', 'Rest the team before the season.',
        { morale: 5, boost: 0.1 },
        'You stay open normal hours.', 'You miss some sales. The team thanks you.'),
    ],
  }),

  sc({
    id: 'rest_curry_powder', biz: 'restaurant', rounds: [5, 14], weeks: 4, when: s => s.brand >= 45,
    title: 'Customers want to buy Amma’s curry powder',
    story: ['“Can I buy the spice mix?” Three people asked this week.'],
    options: [
      o('Launch a product line', 'LKR 600K for packaging and permits.',
        { cash: -600_000, market: 1.08, brand: 6, margin: 0.01, set: ['products'] },
        '“Amma’s Roasted Curry Powder” in kraft-paper packs.', 'They sell out at the counter in days.'),
      o('Sell it in supermarkets', 'LKR 1M including listing fees.',
        { cash: -1_000_000, market: 1.12, brand: 8, margin: 0.015 },
        'Amma’s face on supermarket shelves across the Central Province.', 'Your brand reaches homes you’ll never see.'),
      o('Sell only at the restaurant', 'LKR 100K, a small shelf by the door.',
        { cash: -100_000, margin: 0.01, brand: 2 },
        'A small shelf of spice packs by the cashier.', 'A nice little extra.'),
      o('Keep the recipe secret', 'The mystery brings people in.',
        { brand: 3, quality: 1 },
        '“The recipe stays in the family.”', 'People keep coming back to taste it.'),
    ],
  }),

  sc({
    id: 'rest_branch', biz: 'restaurant', rounds: [8, 14], weeks: 5, when: s => s.customers > s.startCustomers * 1.05,
    title: 'A space near Peradeniya University is available',
    story: ['Ten thousand students. Not one good rice-and-curry place nearby.', 'Fit-out costs LKR 3 million.'],
    options: [
      o('Open a second Amma’s', 'LKR 1M cash, LKR 2M loan. Double the kitchen.',
        { cash: -1_000_000, debt: 2_000_000, capacity: 1.5, market: 1.32, fixed: 120_000, assets: 2_200_000, quality: -2 },
        'Amma’s Kitchen Peradeniya opens with a student menu.', 'Two kitchens. Twice the work.'),
      o('Open a small express counter', 'LKR 900K. Rice packets and kottu only.',
        { cash: -900_000, market: 1.14, capacity: 1.15, fixed: 50_000, assets: 600_000 },
        'A small counter with a short menu.', 'Students queue at lunchtime.'),
      o('Franchise it to a former chef', 'He runs it, you get 8% of sales.',
        { cash: 400_000, market: 1.08, brand: 3, quality: -1 },
        'Your former sous-chef opens it under your name.', 'Low risk, low control.'),
      o('Stay in one place', 'Make the original even better.',
        { quality: 4, brand: 3, morale: 3 },
        'You pass on the space.', 'All your energy stays in one kitchen.'),
    ],
  }),

  sc({
    id: 'rest_renovate', biz: 'restaurant', rounds: [3, 12], weeks: 4,
    title: 'The dining hall looks exactly like it did in 2004',
    story: ['Plastic chairs. A ceiling fan that clicks. Food that deserves better.'],
    options: [
      o('Full renovation', 'LKR 2M, part loan. Close for a week.',
        { cash: -800_000, debt: 1_200_000, customers: 0.85, brand: 8, quality: 4, price: 1.04, assets: 1_200_000 },
        'Wooden tables, warm lights, Amma’s old photos on the walls.', 'It finally looks as good as the food tastes.'),
      o('Paint and new chairs', 'LKR 500K over one weekend.',
        { cash: -500_000, brand: 4, quality: 2, assets: 250_000 },
        'Fresh paint, new chairs, the fan fixed.', 'A small change that people notice.'),
      o('Keep the old look as “retro”', 'LKR 50K for a sign that leans into it.',
        { cash: -50_000, brand: 4, set: ['heritage'] },
        '“Unchanged since 2004. Like the recipes.”', 'Some people find it charming.'),
      o('Spend it on the food instead', 'Better ingredients for every dish.',
        { margin: -0.015, quality: 8, brand: 2 },
        'Better fish, better spices, better rice.', 'The food gets even better. The room does not.'),
    ],
  }),
]
