import { o, sc, n, k, rev } from './kit'
import { TOTAL_ROUNDS } from '../types'

// Scenarios any business can face. Wording adapts to the business.
export const SHARED = [
  sc({
    id: 'any_bailout', biz: 'any', rounds: [2, 14], weeks: 3, needs: ['bailout'], weight: 6,
    title: 'Your bank manager wants a meeting. Today.',
    story: s => [
      'You ran out of cash. The bank covered it with an emergency overdraft.',
      `Your loan is now ${k(s.debt)}. Interest is eating your profit.`,
    ],
    options: [
      o('Restructure the loan', 'Longer terms. Lower weekly payments, more interest overall.',
        // Moves a third of the loan to a long-term facility: less weekly interest, higher total cost.
        s => ({ debt: -s.debt * 0.33, assets: -s.debt * 0.38, morale: 2, clear: ['bailout'] }),
        'The bank stretches your loan over five years.', 'Weekly pressure eases.'),
      o('Sell equipment or space you can spare', 'Raise cash quickly from your assets.',
        s => ({ cash: Math.max(300_000, s.assets * 0.25), assets: -Math.max(300_000, s.assets * 0.3), capacity: 0.95, clear: ['bailout'] }),
        'You sell what you can live without.', 'Cash in the bank. A little less to work with.'),
      o('Bring in an investor', 'Cash for a share of the company.',
        { cash: 3_000_000, assets: -3_300_000, morale: 3, brand: 1, clear: ['bailout'] },
        'A local businessman invests for a 20% stake.', 'Breathing room, with someone looking over your shoulder.'),
      o('Cut costs hard', 'Reduce weekly costs by 15%. The team will feel it.',
        { fixedPct: 0.85, morale: -9, quality: -3, efficiency: 4, clear: ['bailout'] },
        'Hours cut. Projects paused. Every rupee watched.', 'The weekly loss shrinks. So does the mood.'),
    ],
  }),

  sc({
    id: 'any_burnout', biz: 'any', rounds: [3, 14], weeks: 3, when: s => s.morale < 36, weight: 4,
    title: s => `Your ${n(s).team} are exhausted`,
    story: ['Two people called in sick this week. One cried in the storeroom.', 'You can feel it in every shift.'],
    options: [
      o('Hire two more people', 'LKR 35K more a week. Spread the load.',
        { fixed: 35_000, morale: 12, capacity: 1.06, quality: 2 },
        'Two new hires start on Monday.', 'Shifts get lighter. People smile again.'),
      o('Close one day a week', 'Everyone rests together. Lose a day of sales.',
        { capacity: 0.88, customers: 0.92, morale: 14, fixedPct: 0.97 },
        'Closed on Mondays. Everyone rests.', 'The team comes back sharper.'),
      o('Bonus and a team trip', 'LKR 300K. A weekend away together.',
        { cash: -300_000, morale: 15, brand: 1 },
        'A weekend in Trincomalee for the whole team.', 'Stories, laughter, and new energy.'),
      o('Push through this month', 'Promise rest later. Risky.',
        { morale: -4, efficiency: 3 },
        'You ask everyone to push for one more month.', 'They do. Some of them update their CVs.'),
    ],
  }),

  sc({
    id: 'any_cash_pile', biz: 'any', rounds: [5, 14], weeks: 4, when: s => s.cash > 5_000_000,
    title: s => `You have ${k(s.cash)} sitting in the bank`,
    story: ['For the first time, money is not the problem.', 'What you do with it now decides next year.'],
    options: [
      o('Pay off the loan', 'No interest, no pressure.',
        s => ({ cash: -Math.min(s.cash * 0.6, s.debt), debt: -Math.min(s.cash * 0.6, s.debt), morale: 4, efficiency: 2 }),
        'You walk into the bank and clear the loan.', 'Every rupee of profit is now yours.'),
      o('Big marketing push', 'Spend 30% of your cash on a nationwide campaign.',
        s => ({ cash: -s.cash * 0.3, brand: 6, boost: 0.25, market: 1.03 }),
        'Billboards, radio and social media, all at once.', 'People across the country hear your name.'),
      o('Share profits with the team', 'A 20% cash bonus pool.',
        s => ({ cash: -s.cash * 0.2, morale: 16, quality: 4 }),
        'Envelopes on every desk.', 'Loyalty is hard to buy. This comes close.'),
      o('Build something new', 'Invest 40% in a new capability.',
        s => ({ cash: -s.cash * 0.4, assets: s.cash * 0.25, market: 1.15, capacity: 1.15, efficiency: 3 }),
        'New equipment, new space, new reach.', 'A bigger business takes shape.'),
    ],
  }),

  sc({
    id: 'any_power', biz: 'any', rounds: [2, 13], weeks: 4,
    title: 'Power cuts every evening for a month',
    story: s => ['Three hours a day, from 6 p.m.', `Your ${n(s).place} goes dark at its busiest time.`],
    options: [
      o('Buy a generator', 'LKR 900K. Business as usual.',
        { cash: -900_000, fixed: 8_000, assets: 500_000, brand: 2 },
        'A generator hums behind the building.', 'Yours is the only place with lights on the street.'),
      o('Install solar and batteries', 'LKR 1.8M, part loan. Cuts bills forever.',
        { cash: -600_000, debt: 1_200_000, fixed: -18_000, assets: 1_300_000, brand: 3 },
        'Solar panels and batteries go in.', 'Lights stay on, and the bill drops every month after.'),
      o('Change your hours', 'Open earlier, close at 6.',
        { customers: 0.92, fixedPct: 0.96, morale: 2 },
        'New hours, posted everywhere.', 'You lose evenings. You save fuel.'),
      o('Candlelight evenings', 'Turn it into an experience. Risky.',
        { boost: 0.15, brand: 4, quality: -2 },
        '“Lights out at 6. Candles in.”', 'Some people love it. Some can’t see what they’re buying.'),
    ],
  }),

  sc({
    id: 'any_tax', biz: 'any', rounds: [3, 14], weeks: 4,
    title: 'VAT just went up',
    story: ['The budget speech changed the rules. From next month, prices must include the higher tax.'],
    options: [
      o('Pass it on to customers', 'Prices rise 4%.',
        { price: 1.04, brand: -1 },
        'New prices everywhere.', 'People complain, then get used to it.'),
      o('Absorb it', 'Same prices. Lower margin.',
        { margin: -0.035, brand: 2 },
        '“Our prices stay the same.”', 'Customers notice. Your accountant worries.'),
      o('Find the savings inside', 'LKR 300K on a consultant to cut waste.',
        { cash: -300_000, efficiency: 7 },
        'A consultant spends two weeks with your team.', 'Waste you never saw starts to disappear.'),
      o('Premium bundles', 'Repackage products into higher-value bundles.',
        { price: 1.03, margin: 0.01, efficiency: -1 },
        'Bundles and packages replace single items.', 'Higher bills, fewer complaints.'),
    ],
  }),

  sc({
    id: 'any_loan_offer', biz: 'any', rounds: [3, 12], weeks: 4, when: s => s.debt < 6_000_000,
    title: 'A bank offers you a LKR 5 million loan',
    story: ['14% interest a year. Five years to repay.', 'Money now, payments for years.'],
    options: [
      o('Take it and expand', 'More space, more staff, more reach.',
        { debt: 5_000_000, cash: 1_500_000, capacity: 1.25, market: 1.15, fixed: 80_000, assets: 3_000_000 },
        'You sign. Builders and new hires arrive.', 'A bigger business, and a bigger loan.'),
      o('Take it as a safety cushion', 'Keep it in the bank for emergencies.',
        { debt: 5_000_000, cash: 5_000_000, morale: 3 },
        'The money sits in the bank, just in case.', 'You sleep better. Interest is not free.'),
      o('Take half for marketing', 'LKR 2.5M on making your name known.',
        { debt: 2_500_000, brand: 7, boost: 0.3, market: 1.04 },
        'A big campaign launches.', 'More people know your name than ever.'),
      o('Decline', 'Grow from your own profits.',
        { efficiency: 2 },
        'You thank the bank and decline.', 'Slow and steady. No interest to pay.'),
    ],
  }),

  sc({
    id: 'any_poach_manager', biz: 'any', rounds: [3, 13], weeks: 3,
    title: s => `A competitor is trying to hire your ${n(s).manager}`,
    story: ['She knows your customers, your suppliers and your secrets.', 'They offered her 40% more.'],
    options: [
      o('Promote her', 'A new title and a raise. LKR 20K a week.',
        { fixed: 20_000, morale: 7, efficiency: 4 },
        'She becomes operations head.', 'She starts fixing problems before you see them.'),
      o('Give her a share of profits', 'She stays as a partner.',
        { margin: -0.015, morale: 8, quality: 3 },
        'She gets a share of profits.', 'Now she cares about every rupee.'),
      o('Let her go gracefully', 'Wish her well. Hire someone new.',
        { cash: -100_000, efficiency: -5, morale: -2 },
        'A farewell lunch.', 'The new hire needs months to learn the ropes.'),
      o('Match the offer exactly', 'Same job, more money.',
        { fixed: 15_000, morale: 2 },
        'You match it.', 'She stays. Others start asking for raises too.'),
    ],
  }),

  sc({
    id: 'any_viral', biz: 'any', rounds: [3, 13], weeks: 3,
    title: s => `A video of your ${n(s).team} just went viral`,
    story: s => [`One of your ${n(s).team} helped an elderly customer who fainted.`, 'Two million views. People want to visit.'],
    options: [
      o('Ride the wave with a campaign', 'LKR 400K on ads while people are watching.',
        { cash: -400_000, boost: 0.5, brand: 8 },
        'Ads go out within the hour.', 'The crowds are bigger than you can handle.'),
      o('Celebrate the team member', 'A public thank-you and a bonus.',
        { cash: -100_000, morale: 10, brand: 6, boost: 0.2 },
        'You post a heartfelt thank-you and give her a bonus.', 'The internet loves it even more.'),
      o('Launch a community cause', 'Free first-aid training in your area.',
        { cash: -200_000, brand: 9, morale: 4, market: 1.04 },
        'Free first-aid training every month, in your space.', 'You become known for more than business.'),
      o('Stay humble, change nothing', 'Let the moment pass naturally.',
        { brand: 3, boost: 0.15 },
        'You thank people quietly.', 'The attention fades, slowly.'),
    ],
  }),

  sc({
    id: 'any_school_sponsor', biz: 'any', rounds: [2, 13], weeks: 3,
    title: 'A school commerce society asks you to sponsor their event',
    story: ['Three thousand students and parents will attend.', 'They want LKR 250,000.'],
    options: [
      o('Sponsor it fully', 'LKR 250K. Your name everywhere.',
        { cash: -250_000, brand: 6, market: 1.03 },
        'Your logo on banners, T-shirts and the stage.', 'Thousands of families learn your name.'),
      o('Offer internships instead', 'Five students learn real business with you.',
        { fixed: 8_000, brand: 4, morale: 4, efficiency: 1 },
        'Five students join for the holidays.', 'They bring ideas you never had.'),
      o('Give product, not cash', 'Your products as prizes.',
        { cash: -80_000, brand: 3 },
        'Your products are the prizes.', 'Winners post about them.'),
      o('Decline politely', 'Save the money.',
        {},
        'You decline.', 'The money stays in the business.'),
    ],
  }),

  sc({
    id: 'any_pricing', biz: 'any', rounds: [3, 13], weeks: 4,
    title: 'Your accountant says you are underpricing',
    story: s => [`Competitors charge 15% more for the same ${n(s).product}.`, 'You are leaving money on the table, she says.'],
    options: [
      o('Raise prices 12%', 'More per sale. Some customers will leave.',
        { price: 1.12, brand: -1 },
        'Prices go up on the 1st.', 'A few people leave. Most don’t even notice.'),
      o('Raise only for new customers', 'Loyal customers keep their price.',
        { price: 1.06, morale: 1, brand: 1 },
        'Regulars keep old prices. New customers pay more.', 'Loyalty feels rewarded.'),
      o('Add a premium option', 'A higher-priced tier for those who want more.',
        { price: 1.05, quality: 3, efficiency: -2 },
        'A premium version of everything.', 'About a quarter of customers choose it.'),
      o('Keep prices, win on value', 'Grow volume instead.',
        { market: 1.06, brand: 3 },
        '“Same prices. Better every month.”', 'Word spreads about the value.'),
    ],
  }),

  sc({
    id: 'any_supplier', biz: 'any', rounds: [2, 12], weeks: 4,
    title: 'Your main supplier offers 12% off — if you pay a year upfront',
    story: s => [`That is about ${k(rev(s) * 3)} paid today.`, 'Big savings, if they are still around next year.'],
    options: [
      o('Pay upfront', 'Save 12% on supplies. Cash leaves today.',
        { cashW: -3, margin: 0.05 },
        'You pay for the whole year.', 'Every delivery is cheaper. Your bank balance is thinner.'),
      o('Pay six months upfront', 'Half the saving, half the risk.',
        { cashW: -1.5, margin: 0.025 },
        'A six-month deal.', 'A decent saving without emptying the bank.'),
      o('Find a second supplier', 'Make them compete.',
        { efficiency: 4, margin: 0.015, quality: -1 },
        'Two suppliers, competing for your orders.', 'Prices come down. Quality varies.'),
      o('Keep paying monthly', 'Stay flexible.',
        { morale: 1 },
        'You keep things as they are.', 'Cash stays in the bank.'),
    ],
  }),

  sc({
    id: 'any_stock_gap', biz: 'any', rounds: [4, 13], weeks: 3,
    title: 'The cash and the records don’t match',
    story: ['About LKR 400,000 is missing over three months.', 'It could be mistakes. It could be theft.'],
    options: [
      o('Install a proper POS and audit system', 'LKR 600K. Every rupee tracked.',
        { cash: -600_000, efficiency: 8, margin: 0.015, assets: 300_000 },
        'A new system tracks every sale and every item.', 'The gap closes, and you find other waste too.'),
      o('Hire an external auditor', 'LKR 300K. Find out what happened.',
        { cash: -300_000, efficiency: 4, morale: -2 },
        'The auditor finds sloppy record-keeping and one dishonest employee.', 'You fix both.'),
      o('Talk to the team openly', 'Trust first. Free.',
        { morale: 3, efficiency: 2 },
        'You tell everyone what happened and ask for help.', 'The gap shrinks. Not completely.'),
      o('Write it off and move on', 'Focus on growth.',
        { cash: -100_000, efficiency: -2 },
        'You accept the loss.', 'Some leaks continue.'),
    ],
  }),

  sc({
    id: 'any_economy', biz: 'any', rounds: [4, 13], weeks: 5,
    title: 'Fuel prices are up. Customers are spending less.',
    story: ['Everyone is counting rupees this month.', 'Your competitors are cutting prices.'],
    options: [
      o('Launch a budget range', 'Cheaper options for tight wallets.',
        { market: 1.1, price: 0.95, brand: 2 },
        'A “Value” range appears.', 'Customers who were leaving come back.'),
      o('Go upmarket', 'Focus on customers who still spend.',
        { price: 1.07, market: 0.95, quality: 3 },
        'You focus on premium customers.', 'Fewer people, bigger bills.'),
      o('Cut costs and wait', 'Save 8% on costs until it passes.',
        { fixedPct: 0.92, morale: -4 },
        'Spending freeze across the business.', 'You get through it, carefully.'),
      o('Market harder while others cut', 'LKR 500K while competitors go quiet.',
        { cash: -500_000, brand: 8, boost: 0.25 },
        'Your ads run while everyone else goes silent.', 'You are the only name people see.'),
    ],
  }),

  sc({
    id: 'any_rebrand', biz: 'any', rounds: [4, 12], weeks: 4,
    title: 'A design studio says your brand looks outdated',
    story: ['Your logo was made in Microsoft Word.', 'They offer a full rebrand for LKR 800,000.'],
    options: [
      o('Full rebrand', 'LKR 800K. New logo, colours, signage, everything.',
        { cash: -800_000, brand: 11, price: 1.03 },
        'New logo, new colours, new signs.', 'You look like a company that’s going somewhere.'),
      o('Refresh the logo only', 'LKR 250K.',
        { cash: -250_000, brand: 5 },
        'A cleaner version of the old logo.', 'Familiar, but sharper.'),
      o('Ask design students', 'A competition with a LKR 75K prize.',
        { cash: -75_000, brand: 6, morale: 2 },
        'Sixty students submit designs.', 'The winner is brilliant.'),
      o('Keep the old brand', 'People know it. That counts.',
        { brand: -1 },
        'You keep the logo.', 'Nothing changes. Nothing breaks.'),
    ],
  }),

  // ── Final decision (always the last round) ──
  sc({
    id: 'final_board', biz: 'any', rounds: [TOTAL_ROUNDS, TOTAL_ROUNDS], final: true, weeks: 4,
    title: s => (s.rounds >= TOTAL_ROUNDS ? 'One year later. The board wants your plan for next year.' : 'The board wants your plan for next year.'),
    story: s => [
      s.rounds >= TOTAL_ROUNDS ? 'Twelve months. Fifteen decisions. Here you are.' : 'Your last decision.',
      'Investors are in the room. Your final call sets the story they will value you on.',
    ],
    options: [
      o('The growth story', 'Spend to grow fast: new markets, more staff.',
        { cashW: -1.2, market: 1.15, capacity: 1.15, brand: 4, boost: 0.25 },
        'You present a bold plan for new markets.', 'The investors lean forward.'),
      o('The profit story', 'Tighten everything. Show strong margins.',
        { margin: 0.03, efficiency: 8, fixedPct: 0.95, morale: -3 },
        'You present a lean, profitable machine.', 'The numbers speak for themselves.'),
      o('The people story', 'Invest in the team that got you here.',
        { cashW: -0.4, morale: 14, quality: 8, efficiency: 4 },
        'You give the team credit, and a bonus.', 'The investors notice how your people talk about you.'),
      o('The brand story', 'A big launch campaign for next year.',
        { cashW: -0.8, brand: 8, boost: 0.25 },
        'A campaign film premieres in the board room.', 'Everyone in the room remembers your name.'),
    ],
  }),
]
