import { o, sc } from './kit'

// Nexora Solutions — software company, Colombo 03
export const TECH = [
  sc({
    id: 'tech_open', biz: 'tech', rounds: [1, 1], weeks: 4,
    title: 'Your biggest client just left. What does Nexora become?',
    story: [
      'Forty per cent of the work walked out with one email.',
      'Eighteen people are looking at you. They need to hear a plan today.',
    ],
    options: [
      o('Win the client back', 'Offer a discount and a dedicated team. Some work returns.',
        { price: 0.98, customers: 1.2, market: 1.12, boost: 0.3, brand: 2, morale: 4 },
        'You fly to their office with a new offer.',
        'They return part of the work, at a lower rate.'),
      o('Build your own product', 'LKR 1.2M to build retail software you own. Slow, but big.',
        { cash: -1_200_000, market: 1.18, morale: 8, customers: 0.92, brand: 3, set: ['saas'] },
        'Half the team starts building “Nexora POS” for small shops.',
        'Billable hours dip. The team is excited again.'),
      o('Sell to foreign startups', 'LKR 500K on sales in Australia and Europe. Paid in dollars.',
        { cash: -500_000, market: 1.12, price: 1.05, brand: 2, set: ['offshore'] },
        'You start taking video calls with startups in Melbourne and Berlin.',
        'Three sign up. They pay more, and they pay on time.'),
      o('Shrink the team', 'Let four contractors go. Costs fall 15%.',
        { fixedPct: 0.85, capacity: 0.85, morale: -10, efficiency: 5 },
        'Four desks are empty on Monday.',
        'The cash burn slows. The office is quieter.'),
    ],
  }),

  sc({
    id: 'tech_abroad', biz: 'tech', rounds: [2, 8], weeks: 3,
    title: 'Three senior engineers have offers abroad',
    story: ['Canada, Australia, Singapore. Double the salary.', 'They built most of your systems.'],
    options: [
      o('Counter-offer', 'LKR 60K a week more in salaries.',
        { fixed: 60_000, morale: 6, quality: 5 },
        'You match most of the offers.', 'Two stay. One leaves anyway.'),
      o('Give them shares', 'Share options instead of cash. Costs margin.',
        { margin: -0.03, morale: 12, quality: 5, set: ['esop'] },
        'Your senior engineers become part-owners.', 'All three stay. They start thinking like founders.'),
      o('Let them go, promote juniors', 'Cheaper. Quality dips for a while.',
        { fixed: -60_000, quality: -8, morale: 6, efficiency: -4, capacity: 0.9 },
        'Three farewell lunches. Three juniors get promoted.', 'The juniors are hungry, and inexperienced.'),
      o('Offer remote work and a 4-day week', 'Free to offer. Some clients may worry.',
        { morale: 10, efficiency: -3, quality: 2, brand: 3 },
        'Work from anywhere, four days a week.', 'They stay. Your job posts get ten times more applicants.'),
    ],
  }),

  sc({
    id: 'tech_saas_price', biz: 'tech', rounds: [3, 10], weeks: 4, needs: ['saas'],
    title: 'Nexora POS is ready. How do you sell it?',
    story: ['Billing, stock and loyalty for small shops.', 'There are 300,000 small shops in Sri Lanka.'],
    options: [
      o('Free, with paid upgrades', 'Fast sign-ups, slow money.',
        { market: 1.25, price: 0.95, brand: 6, boost: 0.2 },
        '2,000 shops sign up in a month.', 'Only a few pay. Yet.'),
      o('LKR 4,900 a month', 'Fewer customers, real revenue from day one.',
        { market: 1.12, margin: 0.015, brand: 3 },
        'You launch at LKR 4,900 a month.', 'Slow growth. Every customer pays.'),
      o('Partner with a bank', 'A bank offers it free to their business customers. They pay you.',
        { market: 1.18, price: 0.98, brand: 5, set: ['bankpartner'] },
        'A bank bundles Nexora POS with its business accounts.', 'Thousands of shops get it overnight.'),
      o('One-time licence', 'LKR 75,000 per shop, installed by your team.',
        { cashW: 1.2, market: 1.08, efficiency: -3 },
        'Shops pay once, you install it.', 'Cash comes in fast. Nothing comes in next year.'),
    ],
  }),

  sc({
    id: 'tech_saas_vc', biz: 'tech', rounds: [7, 14], weeks: 4, needs: ['saas'],
    title: 'A venture capital fund wants to invest LKR 15 million',
    story: ['For 25% of the company.', 'They want you to grow ten times in two years, whatever it costs.'],
    options: [
      o('Take it and grow fast', 'LKR 15M in the bank. Pressure to spend it.',
        { cash: 15_000_000, assets: -15_000_000, fixed: 150_000, market: 1.25, capacity: 1.4, morale: 4 },
        'Money lands. You hire twelve people in a month.', 'Growth becomes the only number that matters.'),
      o('Negotiate a smaller round', 'LKR 6M for 12%. Less pressure.',
        { cash: 6_000_000, assets: -6_000_000, fixed: 90_000, market: 1.1, capacity: 1.15 },
        'A smaller deal, signed in a week.', 'Enough fuel without losing the wheel.'),
      o('Ask for a strategic partner instead', 'A retail chain invests and becomes your first big customer.',
        { cash: 4_000_000, assets: -4_000_000, market: 1.08, brand: 4 },
        'A supermarket chain invests and installs Nexora POS in 60 stores.', 'Real customers, patient money.'),
      o('Stay independent', 'Grow from your own profits.',
        { morale: 4, efficiency: 4 },
        'You decline the fund.', 'Slower growth, full control.'),
    ],
  }),

  sc({
    id: 'tech_offshore_support', biz: 'tech', rounds: [4, 14], weeks: 4, needs: ['offshore'],
    title: 'An American client wants 24/7 support',
    story: ['They will pay 30% more per hour.', 'Their daytime is your night.'],
    options: [
      o('Start a night shift', 'Pay night allowances. Big revenue, tired people.',
        { price: 1.06, market: 1.12, fixed: 60_000, morale: -6 },
        'A night team logs in at 9 p.m.', 'The client is delighted. The night team is not.'),
      o('Hire a team in another time zone', 'Two contractors in Europe. LKR 80K a week.',
        { fixed: 80_000, market: 1.12, price: 1.05, capacity: 1.1 },
        'Two engineers in Poland cover the gap.', 'Follow-the-sun support, without night shifts.'),
      o('Offer business hours only, at a discount', 'Keep your nights. Earn less.',
        { market: 1.04, morale: 2 },
        'They accept a smaller contract.', 'Everyone sleeps well.'),
      o('Automate the support', 'LKR 700K for monitoring and an AI help desk.',
        { cash: -700_000, efficiency: 8, market: 1.08, brand: 3, assets: 300_000 },
        'Alerts, auto-fixes and a help bot.', 'Most problems are fixed before anyone wakes up.'),
    ],
  }),

  sc({
    id: 'tech_ai', biz: 'tech', rounds: [2, 12], weeks: 4,
    title: 'Clients are asking: can AI do this cheaper?',
    story: ['A client asks why a feature took two weeks.', '“My nephew built something similar in an afternoon with AI.”'],
    options: [
      o('Use AI and cut prices 7%', 'Faster work, lower rates, more volume.',
        { cash: -300_000, price: 0.93, efficiency: 10, capacity: 1.2, market: 1.15 },
        'AI coding tools for everyone. Prices drop.', 'Clients send more work.'),
      o('Sell AI services', 'LKR 800K to build an AI team. Premium prices.',
        { cash: -800_000, market: 1.12, price: 1.04, brand: 5, set: ['ai'] },
        '“Nexora AI”: chatbots and automation for banks.', 'Enquiries arrive from companies you never reached before.'),
      o('Stay human-first and premium', 'Sell quality and responsibility.',
        { quality: 4, brand: 2, price: 1.03, market: 0.96 },
        '“Built by engineers you can call.”', 'Some clients pay more for that. Some leave.'),
      o('Train everyone, keep prices', 'LKR 500K on training. Higher margins.',
        { cash: -500_000, efficiency: 8, morale: 4, quality: 2 },
        'A month of AI training for the whole team.', 'Same price, faster delivery, better profit.'),
    ],
  }),

  sc({
    id: 'tech_tender', biz: 'tech', rounds: [3, 12], weeks: 5,
    title: 'A government tender worth LKR 30 million',
    story: ['A digital system for a ministry. Paid 120 days after each milestone.', 'Ten firms are bidding.'],
    options: [
      o('Bid low to win', 'Win the work, wait for payment, thin margins.',
        { market: 1.28, price: 0.94, cashW: -1.5, morale: -3 },
        'You win. The team is suddenly fully booked.', 'The first payment is months away.'),
      o('Bid with a partner', 'Share the work and the risk with a bigger firm.',
        { market: 1.14, brand: 4 },
        'A large IT firm leads, you build the modules.', 'Less money, less risk, a big name on your portfolio.'),
      o('Bid at full price', 'Probably lose, but every win is profitable.',
        { market: 1.05, brand: 2 },
        'You bid fairly. Another firm wins.', 'The ministry asks you to bid next time.'),
      o('Skip it', 'Focus on private clients.',
        { morale: 2, efficiency: 2 },
        'You stay away from government work.', 'The team stays focused.'),
    ],
  }),

  sc({
    id: 'tech_bug', biz: 'tech', rounds: [3, 14], weeks: 3,
    title: 'A bug locked 2,000 people out of a client’s banking app',
    story: ['It is 11 p.m. on a Friday.', 'The client’s CEO is calling your phone.'],
    options: [
      o('All hands, fix it free', 'The team works all weekend.',
        { cash: -400_000, morale: -6, quality: 6, brand: 3 },
        'Fixed by Sunday morning.', 'The client is relieved. The team is wrecked.'),
      o('Fix it, compensate, publish what went wrong', 'LKR 700K. Full honesty.',
        { cash: -700_000, brand: 8, quality: 8 },
        'A public report: what failed, why, and what changes.', 'Other banks read it. Two ask for meetings.'),
      o('Fix it, bill the overtime', 'It was a rushed change they requested.',
        { cash: 300_000, brand: -4, morale: 2 },
        'You fix it and send an invoice.', 'They pay. They also start talking to other firms.'),
      o('Fix it and build automatic testing', 'LKR 900K so it never happens again.',
        { cash: -900_000, quality: 10, efficiency: 5, assets: 400_000 },
        'Every change is now tested automatically.', 'Releases are slower, and much safer.'),
    ],
  }),

  sc({
    id: 'tech_office', biz: 'tech', rounds: [3, 13], weeks: 4,
    title: 'Your office lease is up for renewal',
    story: ['The landlord wants 15% more.', 'Half the desks are empty on Fridays anyway.'],
    options: [
      o('Move to Rajagiriya', 'A cheaper building. 12% lower costs.',
        { fixedPct: 0.9, morale: -3 },
        'Moving day. Boxes everywhere.', 'Cheaper rent, longer commutes.'),
      o('Go fully remote', 'No office at all. 20% lower costs.',
        { fixedPct: 0.85, morale: 4, efficiency: -5, quality: -2, brand: 2 },
        'Laptops go home. The office is handed back.', 'Freedom for some, loneliness for others.'),
      o('Upgrade to a premium tower', 'LKR 80K more a week. Impress clients.',
        { fixed: 80_000, brand: 8, market: 1.08, morale: 4 },
        'A glass office on the 18th floor.', 'Clients notice. So do job applicants.'),
      o('Move to a coworking space', 'Flexible and 8% cheaper.',
        { fixedPct: 0.94, efficiency: 2, brand: 1 },
        'Hot desks, good coffee, other startups around you.', 'You meet a potential client at the coffee machine.'),
    ],
  }),

  sc({
    id: 'tech_poach', biz: 'tech', rounds: [6, 14], weeks: 4,
    title: 'A giant IT company wants to buy your best team',
    story: ['Five engineers. LKR 3 million paid to Nexora.', 'Those five run your most profitable project.'],
    options: [
      o('Sell the team', 'LKR 3M now. You lose capacity and talent.',
        { cash: 3_000_000, capacity: 0.78, quality: -6, morale: -8, customers: 0.9 },
        'Five people move across town with your blessing.', 'The bank balance looks great. The office feels empty.'),
      o('Refuse and give raises', 'LKR 50K more a week. Keep the team.',
        { fixed: 50_000, morale: 8, quality: 3 },
        'You say no and give the team a raise.', 'They know you chose them.'),
      o('Propose a partnership instead', 'You do subcontract work for the giant.',
        { market: 1.18, price: 0.96, brand: 4 },
        'Nexora becomes their trusted partner for smaller projects.', 'More work, less independence.'),
      o('Let the team decide', 'Share the offer openly. Risky, honest.',
        { morale: 10, capacity: 0.94, quality: -1 },
        'You tell the team everything.', 'Four stay. One goes, with your respect.'),
    ],
  }),

  sc({
    id: 'tech_interns', biz: 'tech', rounds: [2, 12], weeks: 4,
    title: 'Universities want to send you interns',
    story: ['Sixty applications for ten places.', 'Interns are cheap, eager, and need a lot of guidance.'],
    options: [
      o('Take ten interns', 'LKR 30K a week. More capacity, more supervision.',
        { fixed: 30_000, capacity: 1.15, quality: -3, efficiency: -2, brand: 4 },
        'Ten interns arrive with new laptops and big ideas.', 'Senior engineers spend half their time teaching.'),
      o('Run a paid bootcamp', 'Charge for a training course. New income, team distracted.',
        { market: 1.06, margin: 0.01, morale: -2, brand: 5 },
        'The Nexora Code Camp runs on Saturdays.', 'It pays, and you spot your future hires.'),
      o('Take three, train them properly', 'Small, careful, good hires later.',
        { fixed: 9_000, capacity: 1.05, morale: 2, quality: 1 },
        'Three interns, three mentors.', 'All three ask to stay after graduation.'),
      o('No interns this year', 'Protect delivery.',
        { efficiency: 2 },
        'You decline the programme.', 'The team stays focused on clients.'),
    ],
  }),

  sc({
    id: 'tech_scope', biz: 'tech', rounds: [3, 13], weeks: 4,
    title: 'A client keeps adding features without paying',
    story: ['“It’s just a small change.” Forty-two small changes so far.'],
    options: [
      o('Keep saying yes', 'Happy client, tired team.',
        { brand: 4, efficiency: -6, morale: -5 },
        'You build every change.', 'The client sends glowing references.'),
      o('Charge for every change', 'Fair, but the relationship cools.',
        { cash: 300_000, brand: -2, margin: 0.01 },
        'A change-request form, with prices.', 'They pay, grudgingly.'),
      o('Switch to a monthly retainer', 'Fixed monthly fee for ongoing work.',
        { margin: 0.03, market: 1.05, efficiency: 2 },
        'A retainer contract, signed for a year.', 'Predictable money, clear limits.'),
      o('Let the client go', 'Free the team for better work.',
        { customers: 0.9, morale: 8, efficiency: 3 },
        'You end the contract politely.', 'The team cheers quietly.'),
    ],
  }),

  sc({
    id: 'tech_security', biz: 'tech', rounds: [4, 14], weeks: 4,
    title: 'Banks now demand ISO 27001 security certification',
    story: ['Without it, you can’t bid for banking work.', 'It takes six months and costs LKR 900K.'],
    options: [
      o('Get certified', 'LKR 900K. Unlocks banking clients.',
        { cash: -900_000, brand: 7, market: 1.12, quality: 3, assets: 300_000 },
        'Six months of audits and policies.', 'The certificate goes on the wall, and in every proposal.'),
      o('Partner with a certified firm', 'They hold the certificate and take 10%.',
        { market: 1.08, margin: -0.02 },
        'Banking work comes through a partner.', 'You get the work, minus their share.'),
      o('Focus on non-bank clients', 'Retail, education, tourism.',
        { market: 1.03, brand: 1 },
        'You look for clients who don’t need it.', 'A smaller market, no extra cost.'),
      o('Hire a security lead first', 'LKR 40K a week, certification later.',
        { fixed: 40_000, quality: 5, brand: 3 },
        'A security specialist joins.', 'You are ready for the audit when you choose to take it.'),
    ],
  }),

  sc({
    id: 'tech_summit', biz: 'tech', rounds: [5, 13], weeks: 3,
    title: 'You’re invited to speak at a tech summit in Singapore',
    story: ['Two thousand tech leaders in one room.', 'The trip costs LKR 600K. You’d be away for a week.'],
    options: [
      o('Go and speak', 'LKR 600K. Big exposure.',
        { cash: -600_000, brand: 9, market: 1.08, boost: 0.15 },
        'You present how Nexora rebuilt after losing its biggest client.', 'Twelve business cards, three real leads.'),
      o('Send your best engineer', 'LKR 600K. Reward and exposure.',
        { cash: -600_000, brand: 6, morale: 8, market: 1.04 },
        'Your lead engineer gives the talk.', 'She comes back glowing. So does the team.'),
      o('Present online instead', 'Free, smaller impact.',
        { brand: 3 },
        'A video talk from your office.', 'A few people reach out.'),
      o('Decline, focus at home', 'Save the money and the week.',
        { efficiency: 2, morale: 1 },
        'You stay in Colombo.', 'Clients get your full attention.'),
    ],
  }),
]
